### ISSUE TITLE
Zadání pluginu 

### ISSUE THREAD

**Issue by kalich5** [skaut/skaut-google-drive-gallery#1]
1. Na stránkách by měla fungovat galerie ve podobném duchu jako je tahle https://codecanyon.net/item/wp-auto-photo-albums-multi-level-image-grid/5781151 S tím, že by byla přeložená do češtiny a bylo by tam i nějaké další nastavení oproti originálu. 

Řasení složek sestupně nebo vzestupně. To samé u souborů ve složkách. Toto musí být v nastavení odděleno. Další věc jsou jména složek na disku a na stránkách. Na Google Disku se můžou složky opatřovat třeba časovou značkou (příklad: 20170705_) a mělo by jít nastavit co se v názvu galerie nebude zobrazovat. Měl by jít nastavit znak (třeba "_") a to co je před ním se nebude zobrazovat.

2. V nastavení by bylo i napojení na Google Drive do složky kde by měla jednotka uložené fotky. Nejspíše napojení přes Google Drive API (nejspíš OAuth klíč), nastavené přes autorizaci od Googlu, jako to mají i jiné pluginy. Třeba https://codecanyon.net/item/useyourdrive-google-drive-plugin-for-wordpress/6219776 

Zárověň by mělo propojení hlídat všechny změny a případně mazat, přesouvat soubory. Kontrolovat to, co se na Google disku děje.

3. Na zamyšlení je ukládat alespoň nějaké náhledy lokálně na hosting. Pro rychlejší zobrazování by se to hodit mohlo. Pokud ale Google API dokáže i tohle posílat rychle tak je to zbytečné.

Jinak na webu by měla být nová položka menu (Google Gallery) kde by se všechno nastavovalo. Ať je to základní nastavení klíčů od Googlu. Nastavení zobrazování fotek a jejich pořadí (vzestupné/sestupné). Rozlišení náhledů, jejich kvalita, množství na stránce (volitelně i možnost stáhnout originál, podle WordPress úrovně). A další smysluplná nastavení podle toho pluginu na galerii v bodu 1.

Dotazy k zadání na můj email kalich@skaut.cz
Děkuji
Michal Janata

**Comment by slacala** [comment]
Dobrý den měl by jsem pro vás možné řešení. Nevím jaké jsou vaše finanční možnosti, ale NAS pole synology nabízí nejen galerie, ale také možnosti hostovat wordpress. Navíc foto materiál i texty nedáváte do rukou třetí straně jako je Google. 

Kdyby finance byl problém, tak se dá udělat synology NAS ze staršího PC. Ale to je na delší povídání.

Ukázka na webu. Je tam i živá ukázka, ale je jen na 30minut ... 
[](https://www.synology.com/cs-cz/dsm/feature/photo_station)

Pokud by jsem chtěl vědět více a nebo si galerii vyzkoušet mohu vám zpřístupnit mojí NAS galerii pro testování. 

S pozdravem
Lukáš Sláčala

**Comment by kalich5** [comment]
Dobrý den,
děkuji za info. Ale určitě chceme zůstat u propojení s Googlem. Je to pro nás výhodnější a úložiště zadarmo.

Michal Janata

**Comment by slacala** [comment]
Foto galerie zabírají po nějakém čase docela dost místa... google drive zdarma nabízí jen 15 GB, pak už se musí za další GB platit... to u synology odpadá... jste vázaní jen na velikosti svého HDD, ale samozřejmě vaše rozhodnutí respektuji.

**Comment by kalich5** [comment]
My máme neomezený prostor

**Comment by slacala** [comment]
Aha tak to v tomto případě chápu.

**Comment by vojta001** [comment]
3. Budeme-li se API dotazovat dostatečně často (cache maximálně na desítky minut), lze i náhledy tahat přímo z Drive - [https://developers.google.com/drive/v2/reference/files#thumbnailLink](https://developers.google.com/drive/v2/reference/files#thumbnailLink)

**Comment by GenaBitu** [comment]
Rozepsáno do jiných issues
