### ISSUE TITLE
Feature: TinyMCE shortcode editor

### ISSUE THREAD

**Issue by GenaBitu** [skaut/skaut-google-drive-gallery#10]
Make a visual editor for the `sgdg` shortcode. Not sure if that's possible.

**Comment by kalich5** [comment]
Tohle je určitě potřeba, kde se budou vybírat ze které složky se budou načítat fotky a další nastavení Shortcodu.

Musíme myslet i na Gutenberg

**Comment by GenaBitu** [comment]
+1 pro Gutenberg

**Comment by GenaBitu** [comment]
Vyřešeno v 7681b35
