### ISSUE TITLE
Krok 2: Výběr kořenového adresáře File not found

### ISSUE THREAD

**Issue by CmeldaVales** [skaut/skaut-google-drive-gallery#102]
Měnil jsem google účet čili jsem chtěl změnit i Client ID a Client secret
to se podařilo a po Udělení oprávnění to háže tuto chybu. Nevím, zapomněl sem někde něco? nebo si plugin pamatuje tu poslední-již nedostupnou složku a pak ale nemůžu ji já nikde změnit? Zatím klidně i mimoaplikačně.

File not found: 0B5aW9nXfF7-fc2F5VU9Fbi111kU.

**Comment by CmeldaVales** [comment]
Ano úplná odinstalace pomohla. díky

**Comment by GenaBitu** [comment]
Zkusím to opravit přímo v tom pluginu. Díky
