### ISSUE TITLE
Error when "Grant Permission"

### ISSUE THREAD

**Issue by renatosequeira** [skaut/skaut-google-drive-gallery#103]
Hi,

I'm constantly getting an error when i try to grant permission. All the process is done properly, but it fails when i get to the validation of google account i get error500

**Comment by GenaBitu** [comment]
Hi,
thanks for the feedback. Could you please give us more information? Do you get the error after clicking the button on your webpage or after filling out the Google verification? What's the address that gives you the error? Can you please re-check you entered everything correctly in Google app console and in the settings?

Thanks

**Comment by renatosequeira** [comment]
Here's a short video of the whole process.

https://drive.google.com/file/d/1it3rh51-CQjudJJuGbPnLsETD2cLSvMr/view

**Comment by GenaBitu** [comment]
Hi,
this is really weird. In the 500 page, can you please try to manually edit the URL and delete everything after `page=sgdg_basic` and press enter and tell me if it still shows the error?

Do you have any security plugins installed? (WordFence etc.) If yes, can you try to authorize the plugin with them disabled (you can re-enable them afterwards).

Thanks

@kalich5 Any other ideas?

**Comment by marekdedic** [comment]
Hi,
is there any progress on the issue? Would like to get it done :)

Thanks

**Comment by marekdedic** [comment]
Closed for inactivity, might reopen if more info is provided about other plugins present on the site.
