### ISSUE TITLE
Add proper error when the password is wrong

### ISSUE THREAD

**Issue by TheXer** [skaut/skaut-google-drive-gallery#1048]
Hello, 
I have added your plugin into our wordpress website, but we found out quickly that there is almost no error handling when the user writes wrong password. No feedback, anything. Is it possible to add it in new version?

**Comment by marekdedic** [comment]
Hi, I'm not sure what you mean by "wrong password", could you please attach some screenshots?

**Comment by TheXer** [comment]
Sure, here it is: 

![image](https://user-images.githubusercontent.com/76487619/130410934-6862a06d-3eb3-4876-973f-8a0a8d2a697f.png)
Here you see the picture of prompt of password. If I insert wrong password, it should tell me that I've inserted wrong password. Currently, it does nothing and I think it is counterintunitive. Maybe change that?

**Comment by marekdedic** [comment]
Hi,
this password prompt is part of WordPress itself and not something that this plugin changes or even touches. Please open an issue in [WordPress trac](https://core.trac.wordpress.org/newticket).
