### ISSUE TITLE
Closure Notice - Licensing/Trademark Violation: Image and video gallery from Google Drive

### ISSUE THREAD

**Issue by kalich5** [skaut/skaut-google-drive-gallery#1054]
Your plugin has been closed for trademark abuse, which is a violation of our guidelines:

https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/

https://wordpress.org/plugins/skaut-google-drive-gallery/

This means your plugin banner/icons, and/or the display name of your plugin has been determined to be infringement.

In your case, you include official Google logos in your banner. Those are trademarked and must be removed.

What to do next

We understand that this is frustrating to hear, and that having your plugin closed is never a great day. To help restore your plugin as quickly as possible, you are required to do the following:

Remove the use of any of trademarks from the beginning of your plugin's display name
Remove any uses of trademarked logos from your banners and icons
Perform a full security and standards review on your own code
Increase the plugin version
Ensure the 'tested up to' version in your readme is the latest release of WordPress
Update the code in SVN
Reply to this email and request a re-review

Save yourself a lawyer. Don't use someone else's trademark as your domain name, your logo, your plugin name, OR the first term of your plugin name. In addition, do not use trademarked images (like the Google logo) in your banners or icons. Yes, those are considered infringement at this time.

If you do not want to reopen this plugin, reply and let us know. We'll change the closure reason to 'By Author Request' for you.

When we re-review your code we will look at not just the changes, but the entire plugin, so there may be a delay.

Why this is a violation

Trademarks apply to the following aspects of your plugin:

The URL - You may not use someone's trademark in your domain name
The Display Name - You may not begin the display name with someone else's trademarked (or commonly recognized) term and, in some cases, you may not use the name AT ALL.
All Images - You may not use trademarked logos/images in your banner, screenshots, logos, etc.

We also keep our eye on similar names. There's a concept known as brand confusion, so naming your company or plugin similar to another company (like Facerange, say) you can still be legally compelled to change the name. This is why, for example, you cannot use 'pagespeed' in your URL for a site optimization tool, even though Google's only trademark is on 'page speed' (two words). The name is similar enough that we have been required to close plugins.

Whenever we are pressed by a company to close your plugin due to a violation of their trademark, we are forced to do so without prior notice to you.

We apologize for this inconvenience and are working to improve our system to prevent these situations from occurring.

Before you ask “But what about everyone ELSE…” you should be aware that we have been mailing notifications to existing users in batches. A high number of those other developers will end up with their plugins permanently closed due to non-compliance with the guidelines.

Be advised, should you change the name back to one that violates their brand and trademarks after this is resolved, or resume the use of their imagery in your icons and banners, we will close your plugins and suspend your account indefinitely.

**Comment by marekdedic** [comment]
Plugin re-listed with temporary assets, now waiting for all-new assets
