### ISSUE TITLE
Conflict with Official WooCommerce Xero plugin

### ISSUE THREAD

**Issue by nick-stulane** [skaut/skaut-google-drive-gallery#1165]
Hi,

When we are using both plugins
- WooCommerce Xero Integration - Version 1.7.37
- Image and video gallery from Google Drive - Version 2.11.1

We get the following error:
> An error of type E_COMPILE_ERROR was caused in line 13 of the file /home/xxxxxxxx/public_html/wp-content/plugins/skaut-google-drive-gallery/bundled/vendor/guzzlehttp/guzzle/src/ClientInterface.php. Error message: Cannot declare interface Sgdg\Vendor\GuzzleHttp\ClientInterface, because the name is already in use

If we disable the plugin 'Image and video gallery from Google Drive' then Zero works correctly

**Comment by marekdedic** [comment]
Hi,
I'd say this is most probably an issue with incorrectly configured autoloader in the WooCommerce plugin. I could be wrong.

In order to debug this, I'd need to have the plugin source code in my hands. Since it is a paid plugin, I don't.

Have you tried raising the issue with the plugin authors? They might be able to debug this.

**Comment by nick-stulane** [comment]
Thanks, I have contacted WooCommerce and asked them about it.
Did you want me to send you a copy of the Xero plugin for testing?

**Comment by marekdedic** [comment]
Hi,
thanks. If you could send it to me, that would be great - at least I'd be able to tell if this am issue with our plugin, or something WooCommerce need to fix.

Can you email it to me over at developer@dedic.eu please?

**Comment by nick-stulane** [comment]
on the way

**Comment by marekdedic** [comment]
Ok, I've done some initial investigation. The xero plugin uses [jetpack-autoloader](https://github.com/Automattic/jetpack-autoloader) to load its dependencies, instead of the default composer autoloader. If I replace it (in the xero plugin) with composer autoloader, everything seems to work OK...

**Comment by marekdedic** [comment]
I've identified a minor issue in this plugin that caused it to clash with the xero plugin. I was able to fix it, however, do note that the xero plugin does very little to prevent collisions itself. So it may clash with other plugins... :/

**Comment by marekdedic** [comment]
2.11.2 fixes the issue.

**Comment by nick-stulane** [comment]
thanks i will take a look

**Comment by marekdedic** [comment]
Hi,
yeah, we know about the issue in 2.11.2 and 2.11.3 is on the way with a fix. Could you please upgrade (it should land later today or tomorrow) and check again? Is the error message still the same? I was able to fix the error message in backend Xero settings, but because I don't know or use xero, I had no way to actually link it to the plugin...

Thanks

**Comment by nick-stulane** [comment]
using version 2.11.3 if i navigate to
/wp-admin/admin.php?page=woocommerce_xero

I get a the following shown on the page
[Screenshot 2021-12-08 07 50 38](https://user-images.githubusercontent.com/95292618/145169650-13bd3d14-02c6-4d60-abd8-a0c401552165.png)

I then also receive an email with more details
> An error of type E_COMPILE_ERROR was caused in line 13 of the file /home/excelr8motorspor/public_html/wp-content/plugins/skaut-google-drive-gallery/bundled/vendor/guzzlehttp/guzzle/src/ClientInterface.php. Error message: Cannot declare interface Sgdg\Vendor\GuzzleHttp\ClientInterface, because the name is already in use

If I then go to WooCommerce > Orders and try to manually send an order to Xero I get the same error as above (in the wp-admin error log file)
[08-Dec-2021 07:54:26 UTC] PHP Fatal error:  Cannot declare interface Sgdg\Vendor\GuzzleHttp\ClientInterface, because the name is already in use in /home/xxxxxxxxxxxxx/public_html/wp-content/plugins/skaut-google-drive-gallery/bundled/vendor/guzzlehttp/guzzle/src/ClientInterface.php on line 13

**Comment by nick-stulane** [comment]
We have a similar issue on another site but this doesn't use Xero but uses WooCommerce

The page breaks when we use wb bakery and add a woocommerce product to the homepage

![Capture](https://user-images.githubusercontent.com/95292618/145384145-7b41a1d5-2258-407c-955b-df86d9448266.PNG)

[09-Dec-2021 10:56:12 UTC] PHP Fatal error:  Cannot declare class Sgdg\Vendor\Normalizer, because the name is already in use in /home/civiccupco/public_html/wp-content/plugins/skaut-google-drive-gallery/bundled/vendor/symfony/polyfill-intl-normalizer/Resources/stubs/Normalizer.php on line 5

**Comment by marekdedic** [comment]
Hi,
could you please describe the exact situation when the error occurs? Does it only happen with WPBakery? Also, I don't see anything particularly wrong with the screenshot...

**Comment by nick-stulane** [comment]
> Hi, could you please describe the exact situation when the error occurs? Does it only happen with WPBakery? Also, I don't see anything particularly wrong with the screenshot...

Yea in WP Bakery I add a WooCommerce product block and save the page and the whole site breaks and shows the PHP Fatal error.

**Comment by marekdedic** [comment]
Well, WPBakery is a paid product, so could you please send me a zip? I won't use it (I honestly don't see the appeal of page builders...), just use it to debug the problem. Thanks

**Comment by nick-stulane** [comment]
plugin on the way
