### ISSUE TITLE
Conflict with Simple Calendar

### ISSUE THREAD

**Issue by Woromi** [skaut/skaut-google-drive-gallery#1203]
Hi,

when both gallery (2.11.3) and [Simple Calendar](https://simplecalendar.io/) (3.1.31) plugins are activated, the calendar plugin stop working and I get the following error message in email:
` Na řádku č. 31 v souboru /home/vu010130/www/wp-content/plugins/skaut-google-drive-gallery/bundled/vendor/google/apiclient/src/Service/Resource.php došlo k chybě typu E_COMPILE_ERROR. Chybová zpráva: Cannot declare class Sgdg\Vendor\Google\Service\Resource, because the name is already in use`

I'm not sure it this should be resolved here or in the Simple Callendar.

**Comment by marekdedic** [comment]
Hi,
I can't replicate this - I have Simple calendar 3.1.36 and it works fine - could you please check on your side with this (latest) version of simple calendar?

**Comment by Woromi** [comment]
Sorry, I though I have updated version of the plugin. For some reason, updates for Simple Calendar were disabled in Easy Updates Manager and I didn't know it. You are right, it works now.
