### ISSUE TITLE
Feature: video

### ISSUE THREAD

**Issue by marekdedic** [skaut/skaut-google-drive-gallery#13]
Add ability to include videos in gallery (thumbnail + play in preview?)

Maybe special ordering - at the end?

**Comment by GenaBitu** [comment]
https://videojs.com/

**Comment by kalich5** [comment]
To nevypadá vůbec špatně :-)

**Comment by GenaBitu** [comment]
Je připravené ve větvi `video` a čeká na rejas/imagelightbox#152

**Comment by kalich5** [comment]
Jaké formáty videa to bude podporovat?

**Comment by GenaBitu** [comment]
https://www.w3schools.com/html/html5_video.asp

**Comment by GenaBitu** [comment]
Čeká na rejas/imagelightbox#156

**Comment by GenaBitu** [comment]
Čeká na rejas/imagelightbox#158

**Comment by marekdedic** [comment]
Closed by #133 .
