### ISSUE TITLE
Forward and backward buttons squeezed on mobile

### ISSUE THREAD

**Issue by StachRedeker** [skaut/skaut-google-drive-gallery#1304]
When viewing a single image on a mobile device, the forward and backward buttons look squeezed:
![buttons_on_mobile](https://user-images.githubusercontent.com/64889011/158014890-2dfbc3c6-8cc0-43ce-ba73-b2e666ae657f.png)

**Comment by marekdedic** [comment]
Hi,
thanks for the bug report, this definitely shouldn't happen.

We'll look into it, however, I can't promise any timeframe as this is a relatively minor thing :)

**Comment by marekdedic** [comment]
Related: #90, #267

**Comment by StachRedeker** [comment]
> I can't promise any timeframe as this is a relatively minor thing :)

Understandable, don't worry about it.

**Comment by marekdedic** [comment]
Should be covered by marekdedic/imagelightbox#382

**Comment by marekdedic** [comment]
Should be fixed by new releases of imagelightbox, let me know if the issue is still present ;)
