### ISSUE TITLE
Unknown Error has returned

### ISSUE THREAD

**Issue by bchase-woot** [skaut/skaut-google-drive-gallery#1334]
Google Drive Gallery just stopped working. 'Unknown Error' is now occurring again on multiple sites hosted on multiple services. What all is needed for you to provide assistance?

Sample page: https://todaysucks.net/testtesttest/

**Comment by bchase-woot** [comment]
<img width="621" alt="image" src="https://user-images.githubusercontent.com/62617545/161268988-5b9f172a-d2ec-4ad1-b97d-5636c484bf50.png">

**Comment by marekdedic** [comment]
Hi, can you please enable debugging? That way the gallery will print out the full error message.

Thanks

**Comment by bchase-woot** [comment]
Ok, so based on the error; I removed sorting by time however I also had to move all non-MP4 movies (.MOV) out of the folder structure because it gave a 404 error.

Is there a limitation on file types?

**Comment by marekdedic** [comment]
Hi,
there should be no such error no matter the ordering or file types. Could you please post here the error message?

**Comment by marekdedic** [comment]
Hi,
ok, that is strange, could you please try 2 things that could fix it or at least pin-point the issue?
1. Re-install the plugin
2. Try disabling all other plugins. If this fixes the issue, enable them one-by-one to find the one (other) plugin that is incompatible.

Thanks

**Comment by bchase-woot** [comment]
Yeah...had to delete and re-install on 3 different sites....weird
