### ISSUE TITLE
Feature: paging

### ISSUE THREAD

**Issue by GenaBitu** [skaut/skaut-google-drive-gallery#14]
Possible also with "Load more" button

**Comment by GenaBitu** [comment]
Jop, asi dává smysl mít nastavení po kolika se načítají a zda se další načtou automaticky či jen po manuálním stisknutí tlačítka.

Dal bych to jako globální nastavení + #21.

**Comment by kalich5** [comment]
ok, pro zjednodušení to určitě bude dostatečné :-)

**Comment by GenaBitu** [comment]
+ by se mělo napojit na paging Google Drive API

**Comment by GenaBitu** [comment]
Připravené, jakmile bude rejas/imagelightbox#175, tak můžeme mergnout.

**Comment by GenaBitu** [comment]
Closed in 2.5.0
