### ISSUE TITLE
Gutenberg block breaks on folder names starting or ending with a space

### ISSUE THREAD

**Issue by Clausinho** [skaut/skaut-google-drive-gallery#1470]
I want to embed a gallery through the gallery picker. When I click on a certain folder (how this happens I haven't found out yet, one time it was owned by someone else than the oauthed user) I get the error message `Directory "dir" couldn't be found - it may have been deleted or renamed.`
I fixed it last time by renaming the old folder and reuploading it new with the same name.
Screenshots:
![image](https://user-images.githubusercontent.com/5921903/174300929-0d495288-44dc-4529-a284-e78185aa7a0a.png)
I can list the folder, so I assume it must be accessible.
![image](https://user-images.githubusercontent.com/5921903/174300989-70ff123e-e25e-4e5d-8cd8-4acb81c1f317.png)
Clicking on it leads to an error message

**Comment by Clausinho** [comment]
I inspected the path, and that folder had a trailing space. I removed it in Google Drive and now I can access it in the gallery picker.
It appears that this plugin does not support whitespace at the end of the folder.

**Comment by marekdedic** [comment]
Hi, thanks for the report, I can confirm that the picker breaks if the folder starts or end with a space. The gallery still works (if you save the page), but obviously you won't be able to get to any subfolders in the picker...

Thanks for the report!

**Comment by Ivolotti89** [comment]
Can it be updated to a newer version, so the spaces before or after if the folder name won't linger the functionality?

**Comment by marekdedic** [comment]
Hi,
we're working on getting it released as we speak :)
