### ISSUE TITLE
Feature: random image widget

### ISSUE THREAD

**Issue by marekdedic** [skaut/skaut-google-drive-gallery#15]
Open question: is it a good feature?

Random image (from some folder) to be displayed in the sidebar

**Comment by kalich5** [comment]
Ano, to je dobrá věc.

**Comment by kalich5** [comment]
A hodilo by se mít možnost nastavit, ze kterých složky (složek) se mají načítat

**Comment by GenaBitu** [comment]
Nastavení je jasné, předpokládám, že by bylo stejné jako u shortcode.

Můžeš prosím představit nějaké argumenty proč ano?

Argument proti: Já mám totiž vlastně pocit, že widget s náhodnou fotkou je věc, která už se dneska na weby nedává - vlastně jsem to vždycky viděl jenom na starších webech.

**Comment by kalich5** [comment]
Nemyslím vložení jen jedné fotky, ale možnost do nějaké sekce (vodorovný pruh na webu) třeba 5 fotek vedle sebe (s tím, že pod každou bude z které akce je)

Třeba Výroční zpráva na webu střediska s tím, že se tam budou zobrazovat takhle fotky mi přijde jako dobrá věc

**Comment by GenaBitu** [comment]
Umm, není tenhle use-case spíš #16? Asi si to neumím představit tak, jak to popisuješ...

**Comment by marekdedic** [comment]
Seeing as Gutenberg blocks will be coming to widgets, we can close this. If somebody wants a block that displays random images instead of all of them, please open a new issue.
