### ISSUE TITLE
Feature: embedded gallery in pages/posts

### ISSUE THREAD

**Issue by GenaBitu** [skaut/skaut-google-drive-gallery#16]
Open question: Is it a good feature? Isn't it better to leave this to WP core images?

**Comment by kalich5** [comment]
Tohle bych určitě udělal. Fotky co se načítají do médií by měly být ty co patří ke statickému obsahu. Pokud ale bude třeba oddílová akce můžu tam dát pár fotek (které se budou při každém načtení měnit)

A pod to odkaz do galerie, že tam jsou další fotky.

**Comment by GenaBitu** [comment]
Implemented, closing. If there is any other functionality not yet implemented or discussed in another issue, please open a new issue.
