### ISSUE TITLE
Nápověda

### ISSUE THREAD

**Issue by GenaBitu** [skaut/skaut-google-drive-gallery#17]

**Comment by kalich5** [comment]
Vytvoříme nápovědu tady: https://napoveda.skaut.cz/dobryweb/skaut-google-drive-gallery

**Comment by kalich5** [comment]
Jak návod na nastavování, tak vytvoření té Google aplikace

**Comment by kalich5** [comment]
V podstatě tenhle návod co https://florisdeleeuwnl.zendesk.com/hc/en-us/articles/201804806--How-do-I-create-my-own-Google-Drive-App-

**Comment by GenaBitu** [comment]
Jop, víceméně - stačí Drive API
Ty údaje, co tam máš zadat jsou v nastavení toho pluginu (dnes jsem tam přidal i JS origin...)

**Comment by kalich5** [comment]
Co myslíš... https://napoveda.skaut.cz/skaut-google-drive-gallery/ziskani_google_aplikace

**Comment by GenaBitu** [comment]
To je moc pěkné, to snad musí pochopit každý, líbí se mi tam ty obrázky ke všemu... Díky

Detaily:
Ve 4. v tom tučném je překlep: New Proje**c**t
Ve 12. bych asi spíš přes adresu popsal, že to je v administraci v nastavení toho pluginu (než přes ta adresy), nebo třeba obojí - a třeba tam dal ten obrázek ze 13 kde ty údaje jsou ofocené

**Comment by GenaBitu** [comment]
Sesmolil jsem zbytek nápovědy: https://napoveda.skaut.cz/dobryweb/cs-skaut-google-drive-gallery
@kalich5 Mohl bys tam prosím doplnit obrázky? Celkem jsou tam označené 4 (2 nové a 2 zastaralé).
Mohl by se na to prosím někdo podívat a případně doupravit? Udělal bych z toho pak anglickou verzi...
Díky

**Comment by kalich5** [comment]
Tohle je už OK ne?

**Comment by GenaBitu** [comment]
Jojo, takhle to sedí. (Dokud něco nezměníme samozřejmě :) ). Dík za ty obrázky.
