### ISSUE TITLE
Divná zaškrtávací pole

### ISSUE THREAD

**Issue by kalich5** [skaut/skaut-google-drive-gallery#176]
Našel jsem v bloku divná zaškrtávací políčka (viz červené kroužky)
Je tam posuvník, který to zapne. Tak nechápu, co tam dělá ten čtvereček pro zaškrtnutí. 
![Výstřižek](https://user-images.githubusercontent.com/8988898/59827643-85e05000-9339-11e9-9ae6-70d77f85db71.PNG)

**Comment by marekdedic** [comment]
Ahoj, no, věc se má tak.

Ten posuvník vlevo určuje to, zda je za galerie stejně jako globální nastavení toho pluginu, nebo si to určuje sama. Takže když je posuvník vypnutý a ty změníš nastavení centrálně, tak ta galerie se změní taky. A když ten posuvník zapneš, tak si to ta galerie bude řídit sama, tedy nezávisle na tom, co je v globálním nastavení. Zaškrtávací políčko ti pak určuje, jaké je to lokální nastavení.

Když je posuvník vypnutý, je to zaškrtávátko disabled.

Myslím, že tohle není dobré UI, ale nevím, jak to udělat lépe... V angličtině se ta sekce alespoň jmenuje něco jako settings overrides, v češtině to tak jasné není. Problém je prostě v tom, že každé to nastavení (nejen ty zaškrtávací ano/ne potřebuje mít ještě možnost "jako je to globálně"
