### ISSUE TITLE
Nekompatibilita pluginu s pluginem WP-Stateless

### ISSUE THREAD

**Issue by luhas21** [skaut/skaut-google-drive-gallery#1760]
Při využívání ukládání souborů v media library na google cloud s pomocí pluginu WP-Stateless dochází při současné aktivaci pluginu Google Drive Gallery ke kolizím.
https://wordpress.org/plugins/wp-stateless/

**Comment by kalich5** [comment]
@luhas21 teď jsem to zkoušel a přijde mi že to jede v pohodě. Je to ještě aktuální?

**Comment by luhas21** [comment]
Převedl jsem inkriminovaný web na hosting, kde nepotřebuji wp-stateless, takže oba pluginy současně teď nevyužívám.

**Comment by luhas21** [comment]
@kalich5 
Převedl jsem inkriminovaný web na hosting, kde nepotřebuji wp-stateless, takže oba pluginy současně teď nevyužívám.
