### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by kalich5** [skaut/skaut-google-drive-gallery#18]
Složka s překlady nebude nutná. Překlady se budou dělat přímo na WP.org

**Comment by GenaBitu** [comment]
Jo, na něco takového jsem už narazil - ale to může být až to bude publikované na WP.org, ne?

**Comment by kalich5** [comment]
Ano, až to bude publikované
https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/

**Comment by GenaBitu** [comment]
Ok, přehodil jsem to tam, teď to chce pořádně celé přeložit (včetně README, které by v originálu měli být anglický jsem pochopil) po 1.0

**Comment by kalich5** [comment]
Některé části se nepřekládají...

- zobrazení galerie: 12 images
- stránka nastavení, tam je toho víc. Obě modrá tlačítka a i texty než se udělá autorizace

**Comment by GenaBitu** [comment]
To je divné, mně to funguje... Nemůže to být nějak cachované, že by to trvalo, než se ten překlad načte? Protože u mě to má česky (jediné, co jsem nechal anglicky jsou ty 4 pole v kroku 1, která se stejně jmenují v té google console tak mi to přišlo lepší nechat tak jak to uživatelé uvidí tam)

**Comment by kalich5** [comment]
Reinstal, smazání cache, nic nepomáhá. Třeba se to s další aktualizací spraví.

Jinak ty 4 polo rozhodně nechat v AJ :-)

**Comment by kalich5** [comment]
Už vše jede jak má.

**Comment by GenaBitu** [comment]
Ano, akorát až to v budoucnu bude veřejné, tak je dobré to nejprve nahrát na WP.org, přeložit a pak až zveřejnit (aspoň tak jsem pochopil, že funguje to development vs. stable)
