### ISSUE TITLE
after the update yesterday it stop working

### ISSUE THREAD

**Issue by epornhub** [skaut/skaut-google-drive-gallery#1827]
I been using this for a month now and yesterday updates screwed it. It is not working anymore. Just a big round blinking in the page.

https://prnt.sc/K_iJpESMPGrg

**Comment by epornhub** [comment]
https://prnt.sc/UyPD3ykTqxlu and also having this error

**Comment by vadkorte** [comment]
I've been using it for years now, but with the latest update it stopped working, just grey circles are blinking: one for each gallery. Had to roll back to prev version.

**Comment by epornhub** [comment]
I have the same problem. And it gives me like unknown error. I wish developer can notice us.

**Comment by marekdedic** [comment]
Hi, lettin g you know that I know about the issue and I am trying to fix it ;)

**Comment by vadkorte** [comment]
Thank you! Let us know if you need any help e.g. with testing.

**Comment by marekdedic** [comment]
Any chance you both have multiple galleries in the same page?

**Comment by marekdedic** [comment]
Ok, great, then I think know what's wrong :)

**Comment by epornhub** [comment]
Hi,
I normally use 1 gallery per page. Because I tried multiple before the
loading time is so long. So I made it 1 gallery per page.

**Comment by marekdedic** [comment]
Closed in #1831
