### ISSUE TITLE
Minimální verze WP a PHP

### ISSUE THREAD

**Issue by kalich5** [skaut/skaut-google-drive-gallery#19]
**WordPress**
Doplnit funkci, která zabrání aktivování pluginu na starších verzích WP? Aby se dal aktivovat jen na verzi 4.8
Aby ten kdo ho chce použít, musel nejdřív aktualizovat svůj WordPress a neinstalovalo se to na zastaralé verze.
**PHP**
Doplnit funkci, která umožní aktivování pouze na PHP 7.x. Stejně jaké ostatní skautské pluginy.

**Comment by GenaBitu** [comment]
Jo, minimální PHP cílím na 5.4 - zatím tomu zdroják neodpovídá, ale bude :D Je to minimální verze, kterou potřebuje Google API knihovna, takže níže jít nejde.

**Comment by kalich5** [comment]
Chci aby to bylo výš, aby se to nedalo aktivovat pokud tam nebude 7.x Nižší verzi bych podporovat nechtěl, mám zkušenost s Use your Drive, na PHP 7.x to běhá rychleji. A proto bych to chtěl směřovat na tyhle verze.

**Comment by GenaBitu** [comment]
Však to, že to podporuje 5.4 a výš neznamená, že to nemůžeš pustit na 7 abys to měl rychlejší, ne? Pokud tomu tak je, tak nevidím důvod to uměle omezovat (Zvlášt pak, když samotný WP podporuje i nějaké prehistorické verze). Zatím mi to přijde jako větší kompatibilita za žádnou cenu...

**Comment by kalich5** [comment]
Jako i další pluginy co děláme můžou běžet na nižších verzích, než je PHP 7.x Ale omezujeme to, aby jsme lidi nutili používat novější verze.
A pokud jde o nový moderní plugin, můj názor je že by pod 7.x jít neměl.

@jerrysohn @davidulus co myslíte vy dva?

**Comment by kalich5** [comment]
Z hlediska GDPR, budu u vše našich pluginů co už jsou nějakou dobu venku vyžadovat WP 4.9.6 Byl bych rád, aby tohle omezení bylo i tady. (Viz kódy od Davida)

**Comment by GenaBitu** [comment]
Jo, to je asi v pohodě...

**Comment by GenaBitu** [comment]
i když nevím, jak se to týká pluginů...

**Comment by kalich5** [comment]
Prostě ten plugin nejde aktivovat a vypíše hlášku, ať si uživatel aktualizuje WordPress.

**Comment by GenaBitu** [comment]
Ano, ale proč by takovou věc jako GDPR měl řešit naprosto nesouvisející plugin...

**Comment by kalich5** [comment]
Fotky ti přijdou jako nesouvisející? :D Je to pár řádků kódu, přidej to tam prosím. Děkuji

**Comment by GenaBitu** [comment]
Fotky ano, myslel jsem proč to chtít plošně u všech pluginů... Promiň, asi jsem to nenapsal jasně...

**Comment by GenaBitu** [comment]
Ano, to se dostáváš k tomu, oč tu běží - naprosto s tebou souhlasím, že by všichni měli aktualizovat PHP i WP (nejlépe automaticky). Ale jsem toho názoru, že pluginy nejsou to, co by to mělo řešit - plugin má poskytovat funkčnost, ne uměle nutit uživatele do něčeho, co pro funkčnost toho pluginu není zásadní. Už jen třeba proto, že ne všichni uživatelé toho pluginu musí být z organizace...

Já například spravuju jeden web na hostingu farnost.cz a tam až donedávna bylo jen PHP 5.2... Jasně, že mě to štvalo, ale víc než psát maily jsem prostě nemohl...

Asi podle mě v tomto případě účel nesvětí prostředky. Jsem rád, že to IO řeší, ale tohle mi nepřijde jako správné řešení.

**Comment by GenaBitu** [comment]
Třeba v konkrétním přípdadě tohoto pluginu dává podle mě smysl požadovat WP 4.9.6 (kvůli GDPR, jak píšeš), a PHP 5.4...

**Comment by kalich5** [comment]
Dobře, a co kompromis WP 4.9.6 a PHP 5.6 jak máme na Lebedě. Přeci jen PHP 5.4 už je prehistorické a z hlediska bezpečnosti taky nic moc...
