### ISSUE TITLE
Galerie mi brání v napojení na Google

### ISSUE THREAD

**Issue by kalich5** [skaut/skaut-google-drive-gallery#1933]
Používám na webech WPvivid Backup Plugin a je tam napojení na Google Drive. Ale přestalo fungovat a když ho chci znovu konfigurovat, vyskočí na mě okno "Na webu došlo k závažné chybě" a to níže je v Error logu. 

PHP Fatal error:  Cannot declare class Sgdg\Vendor\Google_Task_Composer, because the name is already in use in /DISK3/www/4172/petkapraha.cz/www/wp-content/plugins/skaut-google-drive-gallery/vendor/google/apiclient/src/aliases.php on line 0

Můžeme se na to nějak podívat a pořešit to, aby to funvoalo. Dík

**Comment by marekdedic** [comment]
Je to tohle? https://wordpress.org/plugins/wpvivid-backuprestore/

Pokud ano, tak jsem ho právě nainstaloval, propojil a udělal backup, vše se zapnutou galerií a oběma pluginy aktuálními. Můžeš prosím nějak zjistit, kdy se to děje, abych to mohl replikovat?

**Comment by kalich5** [comment]
Já mám placenou verzi, pošlu hned jak k tomu budu mít přístup.

**Comment by marekdedic** [comment]
Duplikát #1999
