### ISSUE TITLE
Zrušení kořenového adresáře

### ISSUE THREAD

**Issue by kalich5** [skaut/skaut-google-drive-gallery#20]
Chtělo by to mít možnost nezávisle vybírat složky s fotkami z Google Drivu. 

V základním nastavení pluginu jen autorizace (doplnit odkaz na nápovědu)
https://napoveda.skaut.cz/dobryweb/skaut-google-drive-gallery

A nastavení pluginu

**Comment by GenaBitu** [comment]
To mi přijde jako bezpečnostní díra: Při současném stavu (Plugin má kořenový adresář a nic "nad ním" nikdy nebude přístupné z webu) si můžu dovolit jako administrátor webu autorizovat kupříkladu oddílový Google účet s tím, že v něm vytvořím složku (nebo třeba temadrive) a mám jistotu, že nic mimo tuhle jednu složku nikdy nebude na webu (třeba když mám na gdrive stejného účtu nějaké oddílové věci)

**Comment by GenaBitu** [comment]
Původně jsem dokonce přemýšlel nad možností zakázat použití "My Drive" jako kořenové složky, ale pak mi přišlo, že to třeba někdo může tak chtít použít a vlastně proč ne...

**Comment by kalich5** [comment]
Jak to mám přes ten Use your Drive (ten vidí všude, ale je na dokumenty i na fotky)

Musí se pak ale dát jednoduše v nastavení Shortcodu vybrat složka, ze které se bude obsah zobrazovat.

**Comment by GenaBitu** [comment]
Přijde mi to takhle víc "blbuvzdorné" - představuju si to tak, že já to jako administrator takto omezím a jednotliví editoři můžou přidávat shortcody a galerie a fotky a nemůžou omylem zveřejnit něco, co nemají.

Výběr složky bych řešil pomocí #11 a případně možná #12, tam ale nemám jasnou představu, jak by to mohlo fungovat.

**Comment by kalich5** [comment]
Já bych tam ten kořenový adresář zatím nechal. Pokud by lidi omezoval, vyhodil bych ho.

Podle mě je ještě omezující to, že ten shortcode není naklikávací, ale musí se vypsat ručně. Jak třeba zobrazím fotky z roku 2013-2014?
Je to [sgdg path="Fotky/2013-2014"]??

**Comment by GenaBitu** [comment]
No bacha, neumím si představit tohle rozhodnutí v dohledné době měnit - rozbilo by to všechny existující shortcody.
Ale jsem též pro to nechat.

ten argument "path" je cesta k jedné složce, vůbec to nejsou roky, prostě jména složek. Ale v #12 právě řeším, zda tohle stačí, či zda je potřeba něco komplikovanějšího.

**Comment by kalich5** [comment]
Tím pádem bych kořenový adresář nechal. Tím, že je to plugin pouze na fotky (koukal jsem k nám na disky) a máme složku "Galerie" a tam už složky podle let.
Tohle rozhodně nestačí. 

Třeba my máme složku Galerie a v ní 2 složky (Pro veřejnost a Fotky)
Složku pro veřejnost máme na stránce o oddílu

Složka Fotky ze zobrazuje na stránce Archiv fotek. 

Ve složce Fotky máme složky 2012-2013, 2013-2014, atd... prostě podle jednotlivých let. 

A na stránce Aktuální rok máme fotky z roku 2017-2018. Takže tam by vlastně pro nás měl shortcode vypadat: [sgdg path="Galerie/Fotky/2017-2018"]

**Comment by kalich5** [comment]
Takže určitě je potřeba to složitější, viz č.12. A jak už jsem psal, je potřeba mít co nejdřív tohle https://github.com/skaut/skaut-google-drive-gallery/issues/10

**Comment by GenaBitu** [comment]
No a nestačilo by ti teda na stránce o oddílu [sgdg path="Pro veřejnost"], v Archivu [sgdg path="Fotky"] a Aktuální rok jako [sgdg path="Fotky/2017-2018"] ? (předpokládám, že "Galerie" je kořenový adresář).

**Comment by kalich5** [comment]
Jo pravda, to jsem se upsal. Ale i tak potřebuju občas nechat vypsat fotky z nějaké akce. Takže bych stejně potřeboval [sgdg path="Fotky/2017-2018/akce"]

**Comment by GenaBitu** [comment]
Ale to už funguje, můžeš jít jak hluboko chceš.

**Comment by GenaBitu** [comment]
To je #11. Zavírám tuto diskuzi, ale pokud bys měl nějaký use-case, co tohle nepokryje, napiš ho prosím do #12
