### ISSUE TITLE
Error after Granting permission

### ISSUE THREAD

**Issue by slowlyjam** [skaut/skaut-google-drive-gallery#203]
Hello 

I am getting this error when I press Grant Permission:

400. That’s an error.

Error: redirect_uri_mismatch

The redirect URI in the request, https://maroons-jamaica.com/staging2/wp-admin/admin.php?page=sgdg_basic&action=oauth_redirect, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/117142131281-6c7thtnsunv09i6k9pqmnvef2832222f.apps.googleusercontent.com?project=117142131281

Learn more

Request Details
That’s all we know.

How can this be fixed please?

I followed your documentations but cannot get pass this ERROR.
Please help.
Thank you.

Kind Regards

Flavius

**Comment by marekdedic** [comment]
Hi,
this may be a bug on our or your side related to the "Authorised redirect URI". Please check you have copied it to the Google app correctly. If so, could it please send to me? It should be safe to put here publicly, however you can also use my email, developer@dedic.eu.

**Comment by marekdedic** [comment]
No response, closing. Also, please use support on WP.org for support questions ;)
