### ISSUE TITLE
Neznámá chyba

### ISSUE THREAD

**Issue by kalich5** [skaut/skaut-google-drive-gallery#2070]
Tak jsem to zkusil odinstalovat, nainstalovat, znova nastavit, přihlásit a nic... 

![image](https://github.com/skaut/skaut-google-drive-gallery/assets/8988898/e9f4a8e7-8593-4fd7-a439-8346a74b690e)

**Comment by kalich5** [comment]
Pořád neznámá chyba, i v poslední verzi.
![image](https://github.com/skaut/skaut-google-drive-gallery/assets/8988898/1f1c84af-e9c1-46b7-a2d6-976629b334b5)

**Comment by marekdedic** [comment]
Ahoj, upgraduj na 2.13.4 a zapni [debug režim](https://wordpress.org/documentation/article/debugging-in-wordpress/).
