### ISSUE TITLE
Activation latest version (2.13.4) of the plugin ends with a fatal error

### ISSUE THREAD

**Issue by Honny1** [skaut/skaut-google-drive-gallery#2140]
Hello,
activation of the plugin ends with a fatal error, see picture: 
![image](https://github.com/skaut/skaut-google-drive-gallery/assets/26072444/6d082edf-2607-46dc-a41d-b378b2e52636)

- Plugin version: 2.13.4
- Wordpress version: 6.3
- Other plugins: None

I tested installing an older version 2.13.3 and the installation works, but this version suffers from a bug reported in #2070 and #1987.
I turned on debug mode and got this error for issues #2070 and #1987, but that's for version 2.13.3:
```
[{ "error": { "code": 400, "message": "Failed to parse batch request, error: 0 items. Received batch body: (0) bytes redacted", "errors": [ { "message": "Failed to parse batch request, error: 0 items. Received batch body: (0) bytes redacted", "domain": "global", "reason": "badRequest" } ], "status": "INVALID_ARGUMENT" } } ]
```

**Comment by marekdedic** [comment]
Version 2.13.4 had an issue with PHP <8, please update to 2.13.5.

**Comment by Honny1** [comment]
Thank you, the update was successful.

**Comment by marekdedic** [comment]
Glad to hear that and sorry for the inconvenience.
