### ISSUE TITLE
Rozesílání emailu o nových fotkách

### ISSUE THREAD

**Issue by kalich5** [skaut/skaut-google-drive-gallery#22]
V oddíle třeba řešíme, že by bylo super když by se vytvořila aktualita (příspěvek) že jsou nové fotky v galerii.

Nebo, že by se jen poslal email rodičům. 

Ale pokud myslíte že je to blbost, klidně to vypustě...

@sinacek @GenaBitu @jerrysohn @davidulus co myslíte?

**Comment by sinacek** [comment]
to bych asi vypustil klidně

**Comment by GenaBitu** [comment]
Souhlasím se Sinem.
