### ISSUE TITLE
Videa - odlišení od fotek

### ISSUE THREAD

**Issue by kalich5** [skaut/skaut-google-drive-gallery#2336]
Přemýšlím, nedalo by se přes videa dát piktogram "play"? 

Něco takového...
![image](https://github.com/skaut/skaut-google-drive-gallery/assets/8988898/9ed1fe88-16c8-4edf-b4ab-f9c9040affca)

Teď to vypadá takhle a těžko se ty videa odlišují od fotek
![image](https://github.com/skaut/skaut-google-drive-gallery/assets/8988898/9a0c88ce-9fe9-49f3-ab26-ac7e8ae34f95)

**Comment by marekdedic** [comment]
Duplikát #235

**Comment by kalich5** [comment]
No mážná po 4 letech by to chtělo nějaké rozlišení udělat... :D
