### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by GenaBitu** [skaut/skaut-google-drive-gallery#24]
Create a roadmap:
- [x] set milestones:
    - 1.0
    - 1.x
    - 2.0
    - ???
- [x] sort new functionality into milestones
- [ ] deploy 1.0 ASAP

**Comment by GenaBitu** [comment]
Tak co, je 1.0 ready? Nebo je jeśtě něco, co je nutné udělat teď? Vidím to tak, že 1.0 by mohla jít nějakým β-testerům a do 1.1 se musí doladit takové ty serepetičky okolo, aby to uměli používat i BFU...

**Comment by kalich5** [comment]
Já myslím, že to může jít. :-) Přepíšeš readme?

**Comment by GenaBitu** [comment]
Ok

**Comment by kalich5** [comment]
Já jdu na nápovědu, alespoň základ jak udělat tu aplikaci
