### ISSUE TITLE
Máme repozitář

### ISSUE THREAD

**Issue by kalich5** [skaut/skaut-google-drive-gallery#25]
Zažádal jsem o repozitář na wp.org, a už ho máme schválený.

https://cs.wordpress.org/plugins/skaut-google-drive-gallery/

**Comment by GenaBitu** [comment]
Já tam vidím "nenalezeno"...

**Comment by kalich5** [comment]
Hned jak to tam nahraju, bude vidět. Předpokládám, že to co je teď na GitHubu je možné nahrát.

**Comment by GenaBitu** [comment]
No, určitě se ještě bude třeba měnit ten shortcode, takže hrát si s tím někdo může, ale budoucí updaty mu to s největší pravděpodobností rozbijí.
