### ISSUE TITLE
Folder verification checks not always run

### ISSUE THREAD

**Issue by PeterSmith8nss** [skaut/skaut-google-drive-gallery#2510]
As noted in https://wordpress.org/support/topic/second-page-of-shortcut-folder-causing-an-error/#post-17466231 I was getting inconsistent results when using Google shortcuts in the gallery directory.

Code uses Utils::all to make sure results are only returned if the verification AND fetch both succeed. Unfortunately, wp_send_json, used in the onFulfilled handler, causes the thread to die before all promises have been checked. Thus, depending on the order of asynch call execution and return, the verification may or may not been done.

If you replace “wp_send_json( $page )” by “return new FulfilledPromise( $page )” you can defer calling “wp_send_json” until after the “all” aspect of the promise has been evaluated. Then just apply wp_send_json to the first non-null response from “API_Client::execute”. And if verification fails then you will go down the rejected side. And exception will be returned and hence an error returned to the UI.

In a quick test. doing this for Frontend Page and Gallery classes seems to remove the randomness of the folder verify checks.

**Comment by PeterSmith8nss** [comment]
As a test, I modified Page::ajax_handler_body as below. And similar change to Gallery::ajax_handler_body

	public static function ajax_handler_body() {
		list( $parent_id, $options, $path_verification ) = Gallery_Context::get();
		$pagination_helper                               = (
			new Paging_Pagination_Helper()
		)->withOptions( $options, true );
		$raw_path                                        = GET_Helpers::get_string_variable( 'path' );
		$path_names                                      = self::path_names(
			'' !== $raw_path ? explode( '/', $raw_path ) : array(),
			$options
		);
		$page_promise                                    = Utils::all(
			array( Page::get( $parent_id, $pagination_helper, $options ), $path_names )
		)->then(
			static function ( $wrapper ) {
				list( $page, $path_names ) = $wrapper;
				$page['path']              = $path_names;
                                // Changes are all below here....
				//wp_send_json( $page );
				return new FulfilledPromise( $page );
			}
		);
		$result = API_Client::execute( array( $path_verification, $page_promise ) );
		foreach( $result as $res ) {
			if ( $res ) { 
				wp_send_json( $res );
			}
		}
	}

**Comment by marekdedic** [comment]
Ugh, that's a nasty issue. And also some great detective work I have to say! Thanks!
