### ISSUE TITLE
Folder verification fails when using Google shortcuts

### ISSUE THREAD

**Issue by PeterSmith8nss** [skaut/skaut-google-drive-gallery#2511]
If the gallery being displayed contains a Google shortcut to another folder, the plugin will report this folder as not existing when you try and display its contents [Although because of issue#2510 the results may be a bit random].

At the moment "check_directory_in_directory" works by seeing if the parent folder is one of the child folder's parents. But a folder pointed to by a shortcut will report its parent as the actual folder it lives in rather than the folder where the shortcut exists.

[Historically a folder could be in multiple folders. When the revised shortcuts were introduced, a folder only has one parent, although the API field is still an array]

I think the problem could be resolved if instead of getting the child's folder's parent, you fetched an array of all the files (or at least folders and shortcuts to folders) in the parent folder, and looked to see whether the child folder id was in that set.

**Comment by PeterSmith8nss** [comment]
To illustrate what I mean replace code for "check_directory_in_directory" by something like this:

		return API_Facade::list_directories(
			$parent_id,
			new API_Fields( array( 'id' ) ),
			new Single_Page_Pagination_Helper() )->then(
			static function ( $response ) use ( $id ) {
				if ( ! in_array( $id, array_column( $response, 'id' ), true ) ) {
					throw new Directory_Not_Found_Exception();
				}
			},
			static function ( $exception ) {
				if ( $exception instanceof Not_Found_Exception ) {
					$exception = new Directory_Not_Found_Exception();
				}

				return new RejectedPromise( $exception );
			}
		);

**Comment by marekdedic** [comment]
Thanks for the very thorough report, there were actually more issues to do with shortcuts, but hopefully they should be fixed in the linked PR.
