### ISSUE TITLE
Authorisation Error

### ISSUE THREAD

**Issue by tejprokash** [skaut/skaut-google-drive-gallery#2513]
Hi, I am a new user of this plugin. I had a problem while granting permission. Please check this screenshot for reference.
![screrror](https://github.com/skaut/skaut-google-drive-gallery/assets/133680165/deabca95-7f75-4a85-94b2-9d8169be5326)

**Comment by marekdedic** [comment]
Hi, please follow [the docs](https://napoveda.skaut.cz/dobryweb/en-skaut-google-drive-gallery) to see how to set up the plugin - some of the images there are a little bit outdated, but it should generally help you through. Here it seems like you didn't fill in the client ID field?
