### ISSUE TITLE
Known security vulnerabilities detected

### ISSUE THREAD

**Issue by kalich5** [skaut/skaut-google-drive-gallery#27]
We found a potential security vulnerability in one of your dependencies. 

A dependency defined in ./package-lock.json has known security vulnerabilities and should be updated. 

Only users who have been granted access to vulnerability alerts for this repository can see this message.
 Learn more about vulnerability alerts 

https://github.com/skaut/skaut-google-drive-gallery/network/dependencies

Chyba, musí se opravit! Jde o tenhle soubor https://github.com/skaut/skaut-google-drive-gallery/blob/master/package-lock.json

**Comment by GenaBitu** [comment]
Fajn, dík, akorát netuším, která "dependence" to je a z toho seznamu to nezjistím :/

**Comment by GenaBitu** [comment]
No tak to je jquery které je ve wordpressu...

**Comment by kalich5** [comment]
Nevím k čemu tam ten soubor máš, ale už i SIN mi posílal email, že na něj GitHub řve že je tam bezpečnostní chyba.

**Comment by kalich5** [comment]
Tak ten soubor stejně není potřeba pro běh toho pluginu. Takže ho můžu klidně smazat.

**Comment by GenaBitu** [comment]
Ten soubor je potřeba pro vývoj. Takže ne.

https://stackoverflow.com/questions/44552348/should-i-commit-yarn-lock-and-package-lock-json-files/44904494

**Comment by GenaBitu** [comment]
Mělo by být opraveno v rejas/imagelightbox#145 a v 59aa80b
