### ISSUE TITLE
Gutenberg

### ISSUE THREAD

**Issue by kalich5** [skaut/skaut-google-drive-gallery#28]
https://github.com/WordPress/gutenberg

https://make.wordpress.org/core/2018/04/26/your-help-wanted-gutenberg-migration-guide/
https://github.com/danielbachhuber/gutenberg-migration-guide

**Comment by kalich5** [comment]
Nejlepší by bylo pro Gutenberg vytvořit jeden "blok", který tam pak budou uživatelé přidávat.

**Comment by GenaBitu** [comment]
Jojo, tak jsem si to taky představoval :)

**Comment by GenaBitu** [comment]
Zasekl jsem se na WordPress/gutenberg#7016.

**Comment by GenaBitu** [comment]
Uzavřeno v 0850f0f.
