### ISSUE TITLE
Výběr kořenového adresáře

### ISSUE THREAD

**Issue by kucak77** [skaut/skaut-google-drive-gallery#2885]
Zdar,
nevíte někdo jak fixnout bug který se mě při instalaci pluginu stal?
Provedl jsem úspěšně autorizaci, ale nemůžu vybírat z kořenového adresáře.
![image](https://github.com/user-attachments/assets/80c77d46-ee40-4470-9228-7486d919b89e)
Nemáte nějaký nápad čím by to mohlo být?

**Comment by kucak77** [comment]
Opraveno, děkuji za pomoc. Bylo to způsobeno kolizí jiného pluginu a milovaného googlu se zabezpečením.
Vážím si tvojí velmi rychlé reakce ❤️

**Comment by marekdedic** [comment]
Super, který plugin, prosím? Snažím se kolize na naší straně odstraňovat, pokud to jde...
