### ISSUE TITLE
How to use the plugin without Gutenberg editor

### ISSUE THREAD

**Issue by DRYN07** [skaut/skaut-google-drive-gallery#2902]
What is the way of using the plugin without Gutenberg editor? It seems like a simple question, but I couldn't find a solution for it either here or in the documentation.

**Comment by marekdedic** [comment]
Ok, the image links need to be publicly viewable, because that's what the gallery does :D But as I said previously, these links have a relatively short expiration - after around 24 hours, they stop working.
