### ISSUE TITLE
Error since WP 5.3 update

### ISSUE THREAD

**Issue by pharmarin** [skaut/skaut-google-drive-gallery#291]
Hello, 

Since I updated to WP 5.3, I get following error in JS console and block won't load in block editor. 
> Cannot read property 'get' of undefined at SgdgEditorComponent.ajax

I tried reinstall of WP but it didn't work.

**Comment by marekdedic** [comment]
Hi, I'm literally finishing up 2.7.2 at the moment and I think it should fix this issue as well.

**Comment by marekdedic** [comment]
Hi, could you please try in version 2.7.3?

**Comment by pharmarin** [comment]
It works with 2.7.3 update. Thank you.
