### ISSUE TITLE
Odkazy na nápovědu

### ISSUE THREAD

**Issue by kalich5** [skaut/skaut-google-drive-gallery#31]
Odkazy v jednotlivých částích pluginu na nápovědu. 
Hlavní je: https://napoveda.skaut.cz/dobryweb/skaut-google-drive-gallery 

Teď o víkendu asi kus napíšu

Odkaz na Google konzolu: https://cloud.google.com/console

**Comment by GenaBitu** [comment]
https://console.developers.google.com - já používám tohle, na první pohled mi to přide jednodušší, tamto neznám...

**Comment by kalich5** [comment]
Je to asi jedno, tamten můj je komplexní kde se dá nastavit vše. Pro naše potřeby stačí ten od tebe.

**Comment by kalich5** [comment]
@jerrysohn může být napoveda.skaut.cz i v AJ? Abychom tam mohli hodit nápovědu i pro další jazyky.

**Comment by kalich5** [comment]
Jinak já plánuju určitě upravit nápovědu, pokud změníme něco v pluginu.

**Comment by GenaBitu** [comment]
A v https://napoveda.skaut.cz/dobryweb/skaut-google-drive-gallery je potřeba dát obrázek s logem...

**Comment by GenaBitu** [comment]
V 38805ea je nástřel funkčnosti, chybí už jen pravé odkazy na nápovědu.
