### ISSUE TITLE
Testuju MultiSite

### ISSUE THREAD

**Issue by kalich5** [skaut/skaut-google-drive-gallery#35]
Jdu zkusit, jak plugin funguje na MultiSite. Bez toho to na webech nerozjedu.

**Comment by GenaBitu** [comment]
Fajn, tomu moc nerozumím, budu rád za bug-report

**Comment by kalich5** [comment]
Po aktivaci to vypadá dobře. Musím vše propojit, aby byla ověřena 100% kompatibilita.

**Comment by kalich5** [comment]
Tak nefunguje výběr kořenového adresáře. Co jsem zatím zjistil.

**Comment by kalich5** [comment]
12 {

13 "domain": "usageLimits",

14 "reason": "accessNotConfigured",

15 "message": "Access Not Configured. Drive API has not been used in project 772970726736 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/drive.googleapis.com/overview?project=772970726736 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",

16 "extendedHelp": "https://console.developers.google.com/apis/api/drive.googleapis.com/overview?project=772970726736"

17 }

18 ],

19 "code": 403,

20 "message": "Access Not Configured. Drive API has not been used in project 772970726736 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/drive.googleapis.com/overview?project=772970726736 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry."

21 }

22 }

23 in /home/vu009 in /home/vu009026/www/wp-content/plugins/skaut-google-drive-gallery/bundled/vendor/google/apiclient/src/Google/Http/REST.php on line 120

**Comment by GenaBitu** [comment]
Tohle dostaneš kde prosím?

**Comment by kalich5** [comment]
debug log

**Comment by kalich5** [comment]
**Error log**

AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Sgdg\\Vendor\\Google_Service_Exception: {\n "error": {\n  "errors": [\n   {\n    "domain": "usageLimits",\n    "reason": "accessNotConfigured",\n    "message": "Access Not Configured. Drive API has not been used in project 772970726736 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/drive.googleapis.com/overview?project=772970726736 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",\n    "extendedHelp": "https://console.developers.google.com/apis/api/drive.googleapis.com/overview?project=772970726736"\n   }\n  ],\n  "code": 403,\n  "message": "Access Not Configured. Drive API has not been used in project 772970726736 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/drive.googleapis.com/overview?project=772970726736 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our syste...\n', referer: https://petkapraha.cz/wp-admin/options-general.php?page=sgdg

**Comment by GenaBitu** [comment]
A při čem? Při autorizaci?

**Comment by kalich5** [comment]
Autorizace jede v pohodě. Nedá se vybrat kořenový adresář

**Comment by GenaBitu** [comment]
Ok, vím čím to je - nepovolil jsi v google console `Drive API`. Prosím, zatím to nedělej, pushnu patch, aby ti to zařvalo při autorizaci a chtěl bych, abys to pak vyzkoušel.

**Comment by kalich5** [comment]
Aha, tak to se omlouvám. Tak to na to kouknu ještě jednou. Normálně jsem to odkliknul, počkám na patch

**Comment by GenaBitu** [comment]
V poho, naopak dobře, že jsi na to přišel - v tomto případě by ten plugin měl zařvat, že tohle jako teda né... :D

**Comment by GenaBitu** [comment]
Zkus prosím s 5aa6888, mělo by tě to poslat do háje. :D

**Comment by kalich5** [comment]
Super, poslalo mě to do háje

**Comment by GenaBitu** [comment]
Fajn dík. A po povolení tedy MultiSite funkční?

**Comment by kalich5** [comment]
jop
