### ISSUE TITLE
Gallery view

### ISSUE THREAD

**Issue by kalich5** [skaut/skaut-google-drive-gallery#36]
Would you like some nicer view of those galleries. For example, the Czech Zonerama service: https://www.zonerama.com/3jezy/36591 
So I can set up more options as it will look. For example, see the division of more photos Zonerama.

**Comment by GenaBitu** [comment]
Jo, mně by asi sedlo, aby se na to podíval někdo s větším citem pro design... Já tohle tak střílím od boku.

Mně se osobně líbí spíš jednodušší styly jako má http://www.davidbo.dreamhosters.com/?page_id=139 nebo https://aquoid.com/plugins/photonic/.

**Comment by kalich5** [comment]
Ten autoalbum je docela dobrý, chceš ho poslat. Mám ho koupený.

**Comment by GenaBitu** [comment]
Asi v pohodě, designově se tím dá inspirovat i bez zdrojáku... Ale kdyžtak napíšu, dík.

**Comment by kalich5** [comment]
Už máš nasdíleno + našel jsem ještě jeden, tak jsem ti ho nasdílel taky
