### ISSUE TITLE
Úpravy administrace

### ISSUE THREAD

**Issue by kalich5** [skaut/skaut-google-drive-gallery#37]
Představoval bych si, aby se v administraci celá Galerie dostala ven ze složky "Nastavení".

Tedy aby měla svojí položku už v hlavním menu.

Ikonka pro začátek: https://developer.wordpress.org/resource/dashicons/#format-gallery (můžeme zvolit klidně i nějakou jinou, jen takhle mi přišla nejlepší.)
Pojmenování té položky: Google Disk galerie

A pak by tam byly 2 podstránky.
1. První bych nazval: Základní nastavení
Tam by byla autorizace a následně nastavení kořenového adresáře

2. Druhou bych nazval: Nastavení galerie
Tam by bylo všechno co je teď v kroku 3. + další nastavení, které by bylo přidáváno.

**Comment by GenaBitu** [comment]
Jsem takový rozpolcený - to co navrhuješ asi je víc user-friendly v tom smyslu že oddělíš tu nutnou konfiguraci od té "dobrovolné" (které asi bude jen víc), ale zase já vždycky když na nějaký takový plugin narazím tak mě hrozně štve že nemůžu jeho nastavení najít v nastavení (kde má být...) ale ono si to udělá vlastní položku v menu, kterých tam potom mám 3271...

**Comment by kalich5** [comment]
Tak ono jde i o to, že bych do toho pluginu chtěl dostat možnost přiřazování rolí. https://codex.wordpress.org/Roles_and_Capabilities
A po pravdě, v první chvíli když jsem to nainstaloval, tak jsem vůbec netušil kde to nastavení je.

Možná by se hodilo přidělat do administrace i hlášku. 
Třeba: Plugin pro Google Disk galerii je nainstalovaný, ale je potřeba ho ještě propojit. Více info v nastavení" A to slovo nastavení, aby byl odkaz na stránku s tím prvním nastavením.

**Comment by GenaBitu** [comment]
Ten odkaz po instalaci je dobrý nápad...
No nevím, mě to vždycky přišlo naopak divný když to bylo jinde, ale to je subjektivní...

Co bys tam dělal s rolema? Já zatím v nastavení kontroluju, že může nastavovat a jinak nic... Nevím, jestli se dá nějak omezit role pro shortcode...

**Comment by GenaBitu** [comment]
Návrh funkčnosti je ve větvi [admin-pages](https://github.com/skaut/skaut-google-drive-gallery/tree/admin-pages)

**Comment by GenaBitu** [comment]
Bohužel je to ale backwards-incompatible - vyžaduje to změnu Redirect URI v Google Console

**Comment by kalich5** [comment]
Mě se tahle změna líbí. :-)

Jedině pokud bychom to tahle změnily... udělal bych tam pár změn.
1. zamyslet se nad tím, jestli tam nechat v popisech Krok 1: atd...
2. Pokud nebude udělaná autorizace a propojení, nezobrazoval bych "Advanced options", zobrazit až po autorizaci.

**Comment by GenaBitu** [comment]
1. V těch rozšířených určitě ne, spíš bych je ještě nějak rozdělil - zatím to vidím na nastavení toho přehledu galerie a nastavení toho lightboxu
2. Myslíš, že to někoho může zmást? Já bych rozhodně to "advanced" nelezl před "basic"...
