### ISSUE TITLE
Šířka galerie

### ISSUE THREAD

**Issue by kalich5** [skaut/skaut-google-drive-gallery#39]
Při testování jsem narazil na problém. Galerie má prostě 2 sloupce. Tohle by se mělo roztahovat podle toho, jak je stránka široká. 

https://petkapraha.cz/fotky-archiv-test/

**Comment by GenaBitu** [comment]
Galerie by měla mít tolik sloupců, kolik se vejde, viz https://wp-gallery-test.skauting.cz/?sgdg-path=1H88agGMdLoaXxaoA2epZqRMf8nsmrOpI%2F1deNc5fPfjEiWxlon9_-qCOcqQyNX29Vl
Zkus zmenšit velikost miniatur, třeba to pomůže (vejde se)

**Comment by kalich5** [comment]
Přidal bych možnost, nastavit si množství sloupců (třeba 3) a ono to samo dopočítá. To by mi přišlo lepší. :-)

**Comment by kalich5** [comment]
Zrušil bych možnost velikost miniatury. Dal bych tam nějaké výchozí nastavení (kolik sloupců).

A do shortcodu bych doplnil možnost si počet sloupců zvolit. Pro archiv, kde je toho víc se může hodit více sloupců.
Zato aktuální rok, chci třeba s většíma dlaždicema.

**Comment by GenaBitu** [comment]
Jo, no já třeba naopak chci, aby to mělo fixní šířku sloupců a zobrazilo jich to tolik, kolik se vejde...

Ono i teď je to takové na vodě - ty sloupce se přepočítavají na procenta, ale bohužel se do toho započítávají i mezery mezi sloupci, takže jsem to prostě udělal tak, že se to dopočítá do součtu 95%... A ještě jsem tam přidal vyjímku, že pokud je web pod 700px šířky (telefon...), tak to prostě udělá jeden sloupec. Protože jinak to bylo strašně malé...

**Comment by kalich5** [comment]
No ale pak okolo té galerie vznikají divné bílé plochy, protože se to drží toho co se nastavení.

Možná by stálo za to, aby se dalo nastavit třeba 3 sloupce a minimální šířka sloupce. A vždycky, 100% šířky stránky. A plugin by to dopočítával.

**Comment by kalich5** [comment]
Třeba u Use Your Drive se nastavuje výška řádku. + on to sám mění, když je třeba šířka stránky menší.

**Comment by GenaBitu** [comment]
Um, to asi nechápu :D

**Comment by kalich5** [comment]
co přesně na tom jako nechápeš...

**Comment by GenaBitu** [comment]
Jak to funguje v tom Use Your Drive

**Comment by kalich5** [comment]
Nastavil jsem si 3 sloupce https://petkapraha.cz/pro-oddil/fotky-pro-verejnost/

Ale není to na 100% šířky webu... :-(

**Comment by GenaBitu** [comment]
Mělo by být vyřešeno v d4ab057.
