### ISSUE TITLE
Stahování fotek a galerií

### ISSUE THREAD

**Issue by kalich5** [skaut/skaut-google-drive-gallery#40]
Mít možnost stahovat obsah

- [ ] stahování jednotlivých fotek
- [ ] stahování celých alb
- [ ] stahování na základě úživatelské role

**Comment by kalich5** [comment]
https://github.com/Krolloslav

**Comment by kalich5** [comment]
https://github.com/jakubpetrak
Stahování fotek - podle práv wp, nebo skautis

**Comment by GenaBitu** [comment]
Duplikát #81.
