### ISSUE TITLE
Parametr Path

### ISSUE THREAD

**Issue by Krolloslav** [skaut/skaut-google-drive-gallery#41]
Mám problém se špatné fungujícím parametrem path. Pokud ho zadám s uvozovkami tak nefunguje.
[sgdg path="2017-18"] nejde, [sgdg path=2017-18] jde. Prolém je pokud mám název slovy s mezerou. [sgdg path="Fotky z rajčete"] vs [sgdg path=Fotky z rajčete], bohužel ani jeden nefunkční.

**Comment by GenaBitu** [comment]
Aha, to je divný, já to vždycky používal s uvozovkama... Kouknu na to.

**Comment by GenaBitu** [comment]
Ahoj, nedaří se mi toto chování replikovat (funguje mi to s uvozovkama i bez nich, když tam není mezera). Jaký máš WordPress? Případně je na té stránce kromě toho shortcode ještě něco dalšího? Zadáváš ten `path` vzhledem k kořenové složce? (volí se v nastavení)

Díky

**Comment by GenaBitu** [comment]
Můžeš to prosím zkusit s verzí 1.2.0?

**Comment by Krolloslav** [comment]
večer na to mrknu

**Comment by GenaBitu** [comment]
Ahoj, máš nějaký pokrok prosím?

**Comment by GenaBitu** [comment]
Ahoj, pravděpodobně to bylo způsobeno #59 - zkus psát uvozovky ručně a nebo zkopírovat příklad z https://wordpress.org/plugins/skaut-google-drive-gallery/.
