### ISSUE TITLE
Conflict with caching plugins

### ISSUE THREAD

**Issue by GenaBitu** [skaut/skaut-google-drive-gallery#47]
A caching plugin causes a page using the shortcode to not renew the thumbnail links, which in a few hours cease working.

**Comment by GenaBitu** [comment]
Or implementing #32 would solve this completely

**Comment by kalich5** [comment]
Jo, to by mohlo být řešení...

**Comment by GenaBitu** [comment]
cc52de7 prozatím vypíná cachování na jakékoliv stránce obsahující shortcode. Vzhledem k tomu, že chci do budoucna #32 bych to zatím nechal takto.
