### ISSUE TITLE
Pořádné readme

### ISSUE THREAD

**Issue by GenaBitu** [skaut/skaut-google-drive-gallery#49]
Udělat pořádné `readme.txt` - je to stránka pluginu na wp.org

**Comment by kalich5** [comment]
Určitě by se hodilo, máme zatím jen nějaké stručné. Ale pro lepší propagaci by se určitě hodilo. :-)

**Comment by GenaBitu** [comment]
ff4cfae: Chybí správné odkazy na nápovědu, screenshoty... co dál?

**Comment by kalich5** [comment]
nic víc mě nenapadá

**Comment by GenaBitu** [comment]
Můžeme udělat nějakou "demo" stránku?

**Comment by kalich5** [comment]
DEMO WEB: https://demo-skaut-google-drive-gallery.skauting.cz/

**Comment by GenaBitu** [comment]
Ok, takže teď to stojí už jen na #33 pro screenshoty a #31 (umístění anglické nápovědy)
