### ISSUE TITLE
Nefunkční odkaz

### ISSUE THREAD

**Issue by marekbatelka** [skaut/skaut-google-drive-gallery#5]
Odkaz na hlavní stránce vede na "Nenalezeno"

https://cs.wordpress.org/plugins/skaut-google-drive-gallery/

**Comment by kalich5** [comment]
ještě to není hotové, tak to tam nemůže být.

**Comment by marekbatelka** [comment]
A nechceš tam napsat někam "work in progress?" Při procházení pluginů jsem nabyl dojmu, že to je ready.

**Comment by marekbatelka** [comment]
Rozumím - OK
