### ISSUE TITLE
Co se stane při přidání bloku když není plugin nastaven?

### ISSUE THREAD

**Issue by GenaBitu** [skaut/skaut-google-drive-gallery#50]
Asi by se měla zobrazit nějaká hláška, co uživatele pošle do nastavení...

To samé pro TinyMCE plugin

**Comment by kalich5** [comment]
Něco jako máme v tom skautIS pluginu. Dokud to člověk nenastaví, furt svítí nahoře hláška. S odkazem na nastavení.
