### ISSUE TITLE
Třídění fotek

### ISSUE THREAD

**Issue by kalich5** [skaut/skaut-google-drive-gallery#55]
Na starém webu jsme měli funkci třídění podle jednotek v oddíle. Mladší Jeleni a starší Pětka.

Nově to mám teď udělané tak, že v názvu máme na konci "- SP" "- Jeleni" a "- Středisko" a to rozlišuje, koho se to týká.

V nastavení pluginu si zvolit kategorie pro třídění podle nějakých pravidel z názvu složky.
A pak v zobrazení galerie by se na začátku vedle sebe ukazovaly názvy těch kategorií a vedlo toho počet alb v každé.
Př:
Starší Pětka - 5   Jeleni - 10    Středisko - 2

A vedle toho by bylo políčko na zaškrtnutí, a podle toho by se zobrazovaly vybrané galerie. Určitě by bylo dobré, aby se tohle nastavení projevovalo i v URL, aby se třeba ze sekce pro mladší členy dalo odkázat na personalizovanou stránku s fotkama. Ale aby to byla pořád ta jedna, jen tam bude vybrané galerie jen těch mladších.

**Comment by GenaBitu** [comment]
Přijde mi to příliš specifická funkčnost na to, aby to mělo širší využití, a zároveň relativně složitá věc. Kdyby bylo hotové #12, nestačilo by ti to k vytvoření něčeho použitelného? (Třeba stránka s kompletní galerií a tři podstránky s galeriemi jednotlivých jednotek...)

**Comment by kalich5** [comment]
Obecně jsem myslel nějak mít možnost tagovat složky. Můžu mít i jiné pravidlo, jen mě nenapadá teď jaké. :-)

**Comment by CmeldaVales** [comment]
K tomu třídění. Je fajn mít nějaké obecné settings.
Ale dost často se stává že zrovna tuto zobrazenou galerii u jednoho článku chci mít řazenou jinak. Plánuješ/neplánuješ přidat do shortcode nějaké nastavení řazení u konkrétního zobrazení?
PS: řazení podle data není jednoznačné, je totiž rozdílný atribut (datum Vytvořeno, datum Upraveno) podle mého zjištění si asi používal Upraveno.

**Comment by GenaBitu** [comment]
Ahoj, ano, přemýšleli jsme o tom - #21.
Řazení podle data je skutečně podle úpravy.

**Comment by GenaBitu** [comment]
Uzavírám. Možnost změny pro konkrétní galerii je už implementována. Zbytek je rozepsán v #83 .
