### ISSUE TITLE
Pár nápadů

### ISSUE THREAD

**Issue by Sroubek2** [skaut/skaut-google-drive-gallery#58]
1. **Zobrazení videí** (z akce točíme i videa, tak bychom je chtěli vložit do alb – alespoň 720p) - https://github.com/skaut/skaut-google-drive-gallery/issues/13

2. **Kulaté šipky u posuvníků**, ať to vypadá více skautsky (podle skautského grafického manuálu)

3. **Zjednodušení a kratší link** (odkaz na fotky je zbytečně dlouhý)

4. **Profesionálnější třídění** (Něco ve stylu Rajčete, kde se dá jednotlivou fotku samostatně seřadit – většinou fotí více fotografů a názvy fotek se liší, proto se musí zdlouhavě přejmenovávat fotky)

**Comment by kalich5** [comment]
2. Tohle je podle mě úplně jedno, pokud bude nějaká změna zobrazení, může se zapracovat

3. Vycházíme z toho co nám posílá Google. @GenaBitu nebo to jde zkrátit...? podle mě to nevadí

4. Třídění probíhá na Google Disku. Takové pokročilejší třídění jsem popsal tady: https://github.com/skaut/skaut-google-drive-gallery/issues/55

**Comment by Sroubek2** [comment]
3. Podle mě, by bylo lepší. Třeba pro sdílení alba na sociálních sítích, nebo v mailu. Polovinu textu zabírá link, ale jestli to nejde, tak se nedá nic dělat :). Dávám jenom nápady a nevím jestli jsou vůbec zrealizovatelný :D.

**Comment by Sroubek2** [comment]
2. <3

3. No, teď když jdu do určitého alba, tak link je šíleně dlouhý pro sdílení sociálních sítích, nebo pro maily

**https://něco.skauting.cz/fotografie/?sgdg-path=1QAvqVoNczpe4yXZLDGFXirUpbzz72L7T/1EVbm9SA8CXRqRKsx3mHJ264JBk-kyHnn**

místo toho, by mohlo být 

**https://něco.skauting.cz/fotografie/názevsložky1/názevsložky2**

pozn. "_fotografie"_ je jenom nepodstatný příklad

4. Přetahovat libovolné fotky, tak jak je chci mít na webu seřazené (ale tohle je nejspíš nereálné, protože to vlastně zobrazuje z google disku)

**Comment by GenaBitu** [comment]
3. Složky můžou měnit názvy, takže používáme ID... Možná by to šlo přepisovat jako cestu místo jako parametr, ale délce to moc nepomůže (smazalo by se `?sgdg-path=`), ale víc nejde.
4. Můžeme přidat víc možností řazení do nastavení, ale určitě nechci dělat manuální řazení - ten plugin je dělaný tak, aby pouze zobrazoval obsah a nijak ho neupravoval nebo nevytvářel - chtěl bych, aby to tak zůstalo.

**Comment by Sroubek2** [comment]
Jasně chápu :) to přejmenování mě nenapadlo :)

**Comment by kalich5** [comment]
4. Jako třídění jsem měl nápad třeba na tohle https://github.com/skaut/skaut-google-drive-gallery/issues/55 to by mohlo pomoct. Podle parametrů a názvu té složky. :-)

**Comment by GenaBitu** [comment]
Přijde mi, že 1. je řešená #13, 2. je vyřešená, 3. je teď o něco lepší a dál už to lepší nebude a 4. je řešená #55 / vyřešená.
