### ISSUE TITLE
.mp4 video not working

### ISSUE THREAD

**Issue by adamjanovsky** [skaut/skaut-google-drive-gallery#618]
Hi, 

Is there any documentation on how adding videos to the galleries should work? I created a folder on GDrive, added couple of photos there together with tvo `.mp4` videos. While the gallery displays properly, the videos (even the thumbnails) are missing. 

Is that because mp4 is unsupported format? If yes, could it be possible to document how to work with the videos? I did not find a word about videos in the documentation. 

Thanks a lot for yor response.

**Comment by marekdedic** [comment]
Hi,
there’s a temporary limitation on videos over certain size – they must be set to “Anyone with a link can view” permission.

Hope this helps

**Comment by adamjanovsky** [comment]
> Hi,
> there’s a temporary limitation on videos over certain size – they must be set to “Anyone with a link can view” permission.
> 
> Hope this helps

Thanks a lot, it indeed helped. Acquiring a _share link_ resulted in the video displaying correctly. Freel free to close the issue. 

However, I'm wondering how is this a _temporary_ limitation? Is it posed by Google and expected to be fixed in forseeable future?

**Comment by marekdedic** [comment]
There's a workaround, just not implemented it yet... And yes, it's a limitation by Google.
