### ISSUE TITLE
Panoramatické fotky

### ISSUE THREAD

**Issue by kalich5** [skaut/skaut-google-drive-gallery#63]
V náhledu na mobilu se špatně zobrazují panoramatické fotky. WEB: https://fotky.prosek.org/fotky-ze-salzy-panorama/
![38151456_2611191762239532_2987070731264720896_n](https://user-images.githubusercontent.com/8988898/43630774-88bbf3ea-9701-11e8-9356-ebef0bc5448a.jpg)

**Comment by GenaBitu** [comment]
Vyřešeno v 2.2.3
