### ISSUE TITLE
Více galerií na jedné stránce

### ISSUE THREAD

**Issue by kalich5** [skaut/skaut-google-drive-gallery#64]
Nedá se vložit víc galerií na jednu stránku. viz: https://demo-skaut-google-drive-gallery.skauting.cz/more-galleries-on-one-page/

DEBUG: PHP Notice: Constant DONOTCACHEPAGE already defined in /home/vu009901/www/wp-content/plugins/skaut-google-drive-gallery/frontend/shortcode.php on line 26

V návaznosti na to se nedá přidat druhý blok Galerie v Gutenbergu.

**Comment by kalich5** [comment]
![38226989_2613944518630923_4190981048227594240_n](https://user-images.githubusercontent.com/8988898/43676292-925c5eba-97ee-11e8-9bdc-b7a66672173a.jpg)

**Comment by kalich5** [comment]
Ještě jedna ukázka: https://fotky.prosek.org/pokus-galerie/

**Comment by GenaBitu** [comment]
Duplikát #48

**Comment by jakubpetrak** [comment]
Opět stejný problém. Tentokrát jen při tvorbě příspěvku. 

Při postupu:
1. Tvorbra článku
2. Vložení galerie1
3. Vložení galerie1 za galerii 2
4. Přesunutí galerie1 před galerii 2
5. Přidátí textů První galerie a Druhá galerie

...tak to prostě zase začalo fungovat... Teda tvářilo se to tak...

![snimek obrazovky 2018-09-20 v 8 09 56](https://user-images.githubusercontent.com/43341654/45799096-9d0be780-bcac-11e8-9d26-f322b60a5169.png)

Nicméně na stránce https://fotky.prosek.org/problem-vice-galerii/ chyba "Kořenová složka galerie neexistuje – mohla být smazána nebo přejmenována."

Navíc nyní první galerie ovlivňuje (přepisuje) obsah druhé.
![image](https://user-images.githubusercontent.com/43341654/45799253-23282e00-bcad-11e8-847d-d259beddb938.png)

**Comment by GenaBitu** [comment]
Ahoj,
více stejných galerií na jedné stránce nefunguje - o tom vím, ale v tuto chvíli jsem neplánoval to opravit.
Vážně potřebuješ víckrát stejnou galerii?

**Comment by GenaBitu** [comment]
Ahoj, potvrzuji, jsem schopný problém replikovat.

**Comment by GenaBitu** [comment]
Opraveno v 4c0a20b.
