### ISSUE TITLE
Samostatná fotka?

### ISSUE THREAD

**Issue by CmeldaVales** [skaut/skaut-google-drive-gallery#66]
Je mi jasné že primárně tento plugin řeší zobrazení celých galerií.
Ptám se a dávám na zvážení možnost vložit právě jednu fotku z galerie.
Při psaní článku, rozumějme hezky stylyzovaných článků, je třeba dávat fotky, obrázky jednotlivě do textu a na závěr vložit galerii.

**Comment by kalich5** [comment]
Jasný no, je to něco jako tohle: https://github.com/skaut/skaut-google-drive-gallery/issues/15 (náhodná fotka ve widgetu)

**Comment by GenaBitu** [comment]
Ahoj, pokud tím myslíš jednu konkrétní fotku, tak bych využil funkčnosti WordPressu a vložil ji prostě jako obrázek. Pokud tím myslíš jednu náhodnou fotku z galerie, tak to je něco, nad čím můžeme uvažovat, jak toho dosáhnout. :)

**Comment by CmeldaVales** [comment]
Ne, myslím v průběhu článku vkládat jednotlivé fotky z načtené galerie.
Chápeš.
píšeš článek a ilustrativně v odstavečku přidáš fotku, v dalším odstavečku ještě jednu a na konci článku najdeš celou galerii z akce.
V tebou popisovaném případě bych musel tyto dvě fotky samostatně vložit do WP-media a pak vkládat do článku. Já naopak chci využít toho úložiště. abych fotky nemusel nahrávat do WP a přesto je v článku zobrazit.

**Comment by jakubpetrak** [comment]
Teda asi něco jako toto? #85 (přičemž obrázky by se teda narozdíl od úvodní fotky nekopírovaly do wp, ale byly pouze na googledisku)

**Comment by GenaBitu** [comment]
Ahoj.
Klonil bych se k variantě, kdy můžeš do WP-media interaktivně kopírovat fotky z Disku. Tedy píšu článek, chci tam vložit fotku, tak ji v dialogu označím, ona se mi prokopíruje do WordPressu a vloží do stránky.

Asi to ale nemám ještě úplně vyjasněné, tedy pokud někdo myslíte, že by bylo lepší vytvořit blok/shortcode pro jednotlivou fotku opravdu z Disku, argumentujte.

**Comment by GenaBitu** [comment]
Z mailu od @jakubpetrak:

Myšlenka kroniky - prostě tohle je pecka, dělat kroniku z fotek rovnou na webu a využívat již jednou nahraných fotek. Jak by to mělo fungovat? Myslím, že jsem to popisoval - sosnout z drivu fotku a uložit do wp adresáře - pro titulní fotku. No a potom pro další fotky je to otázkou - asi jako link na jednotlivé fotky na galerii. Kdy po rozkliknutí by pokračovala galerie na další fotky, ...
Současně by se pak k tomu hodilo mít možnost vložit jenom galerii dalších fotek, aby nebyly vysypaný do konce stránky, ale byla to třeba jako složka... Bez toho aniž bych takovou pomocnou složku musel fyzicky vytvářet.

**Comment by marekdedic** [comment]
Closed in favor of #191, if anyone feels that would be an insufficient solution to the problems outlined here, please open a new issue.
