### ISSUE TITLE
chyba instalace

### ISSUE THREAD

**Issue by CmeldaVales** [skaut/skaut-google-drive-gallery#67]
ahoj, nevím jestli se to netýká jen mého webu, ale při aktivaci pluginu to píše:

> Plugin nemůže být aktivován, protože způsobil závažnou chybu.
> Parse error: syntax error, unexpected '[' in /pub/#######/#######.cz/web/######/wp-content/plugins/skaut-google-drive-gallery/skaut-google-drive-gallery.php on line 54

máte odhad jestli je to jen u mě nebo je to něco v pluginu?
některé další pluginy také hází chybu, ale jiné se bezproblémů aktivujou

WordPress 4.9.8, přeinstalovaná odznova, žádný plugin aktivovaný

**Comment by GenaBitu** [comment]
Ahoj, jakou máš prosím verzi PHP?

**Comment by CmeldaVales** [comment]
Ano ano, omlouvám se, moje chyba .. já blbec sem si na této doméně nezvýšil PHP. měl sem 5.4 nastavil sem 5.6 a v pořádku se aktivuje.
**Mea culpa**

**Comment by kalich5** [comment]
@GenaBitu možná by bylo dobré tu hlášku nějak upravit... ;-) aby to bylo srozumitelné.

**Comment by GenaBitu** [comment]
Ahoj, no ono moc není jak ji upravit - ten plugin prostě není platné PHP 5.4 a WordPress tohle před instalací nekontroluje (https://core.trac.wordpress.org/ticket/40934). Takže to hodí PHP chybovku. V tom pluginu je implementovaná kontrola verze PHP při aktivaci - tak daleko se ale na 5.4 ani nedostaneš.

**Comment by kalich5** [comment]
ok, tak se tím nebudeme už dále zabývat.
