### ISSUE TITLE
Your site doesn't include support for the "skaut-google-drive-gallery/gallery" block. You can leave this block intact or remove it entirely.

### ISSUE THREAD

**Issue by midifinger** [skaut/skaut-google-drive-gallery#672]
I am getting this message: Your site doesn't include support for the "skaut-google-drive-gallery/gallery" block. You can leave this block intact or remove it entirely.

The old pages I created still work, but now I cannot add any new pages or edit any one ones.

**Comment by marekdedic** [comment]
Hi,
just tried it and works for me... So, let's try to narrow down the issue:
- What WP version are you using?
- What plugin version are you using?

**Comment by midifinger** [comment]
Thank you for helping me.
WP 5.5.1
Plugin 2.9.0
When I view existing old pages it works, but when I try to edit those pages or create a new page and use the plugin, I get the error above.

**Comment by marekdedic** [comment]
Hi,
could you please try re-installing the plugin? Also, could it be caused by interacting in some bad way with other plugins? Could you try turning them off?

Thanks

**Comment by midifinger** [comment]
Turning off the other plugins didn't change anything I will try to re-install. Thank you.

**Comment by marekdedic** [comment]
And just to be sure... Is the plugin installed & activated?

**Comment by marekdedic** [comment]
Hi, any progress with this?
