### ISSUE TITLE
Add option to have images with titles

### ISSUE THREAD

**Issue by marekdedic** [skaut/skaut-google-drive-gallery#68]
https://wordpress.org/support/topic/add-titles-from-google-drive/#post-10613435

**Comment by serycjon** [comment]
I will try to implement this using the "description" metadata field, which can be easily accessed from the gdrive web interface as well.  When enabled, the descriptions could be shown on a small overlay over the bottom of the image (probably only when showing single image?).

**Comment by GenaBitu** [comment]
Hi, this looks very good, thank you. I still need to checkout the code on an actual webpage, but from a quick look over the code it should work.
Translations are done later when a new version is published using the [online translator](https://translate.wordpress.org/projects/wp-plugins/skaut-google-drive-gallery).

Thanks for the first PR!

**Comment by marekdedic** [comment]
Closed by #106
