### ISSUE TITLE
Feature: ordering

### ISSUE THREAD

**Issue by GenaBitu** [skaut/skaut-google-drive-gallery#7]
Possibly order by:
- filename
- time
- filename prefix
- ??? random

ascending/descending

**Comment by kalich5** [comment]
Nejdůležitější je to, že řazení složek a obsahu musí být různé.

**Comment by kalich5** [comment]
Řazení složek sestupně nebo vzestupně. To samé u souborů ve složkách. Toto musí být v nastavení odděleno. Další věc jsou jména složek na disku a na stránkách. Na Google Disku se můžou složky opatřovat třeba časovou značkou (příklad: 20170705_) a mělo by jít nastavit co se v názvu galerie nebude zobrazovat. Měl by jít nastavit znak (třeba "_") a to co je před ním se nebude zobrazovat.

**Comment by GenaBitu** [comment]
Ano, řazení složek vs. řazení obrázků - přijde ti dostatečné mít možnost (ne)předřadit složky obrázkům? Viz #9.

**Comment by GenaBitu** [comment]
Superseded by #43 and #44
