### ISSUE TITLE
Řazení složek ovlivněné ne/přítomností fotek

### ISSUE THREAD

**Issue by kalich5** [skaut/skaut-google-drive-gallery#70]
Když ve složce galerie jsou složky a fotky, tak je řazení podle fotek. 

Nejlepší by bylo přidat řazení kdy jsou ve složce fotky i složky. A pokud ne, tak v takovém případě řadit podle složek. Takže ty složky by se měly řadit 01, 02,... a né jako je to teď. 05, 04,...

![bez nazvu](https://user-images.githubusercontent.com/8988898/44525185-732cc880-a6e0-11e8-9d44-74332cf18fa5.png)

**Comment by GenaBitu** [comment]
Asi to úplně nechápu...

Současný stav:

Složky jsou na začátku, pak fotky. Obojí je řazené nezávisle na tom druhém, dle svého vlastního nastavení (podle názvu/data, vzestupně/sestupně).

Pokud máš pocit, že tomu tak není, tak je to chyba. Pokud jenom chceš přidat další možnosti, tak je to feature request. Teď moc nevím, které to je.

**Comment by kalich5** [comment]
Tak teď jsem si hrál s nastavení a asi vím, čím to je. Ono u toho Use Your Drive je to tak, že když je tam jedna fotka, už je to řazení podle fotek, takže vzestupně. (takže složky jsou 01, 02,... a pak obrázky)

Jenže jak my to máme rozdělené, tak ty složky se řadí podle toho jak to má být. Že na začátku je poslední výprava, tedy největší číslo. (proto je tam ta 05, 04...)

Tím pádem je tohle nová funkce, mít možnost si zvolit řazení pro případ, že jsou ve složce jak další složky tak i fotky.

**Comment by jakubpetrak** [comment]
Řešil by to asi shortcode pro nastavení řazení složek a fotek jen pro galerii obsahující pouze tábor? Tady se ale ukazuje druhý problém: Pravdou je, že když složka Tábor obsahuje složky s jednotlivými dny (Tábor/Pondělí, ...), nebo složky podle toho kdo fotil (Tábor/FotilX, ...), tak se bohužel galerie zobrazí jen jako složka a nemá žádný obrázek, což svádí k tomu použít aspoň jednu fotku, kterou nahraju do Tábor/fotka.jpg, nicméně ta by se klidně nemusela zobrazovat v galerii, nebo by to mohla být právě náhodná fotka z podsložek "fotil".

**Comment by GenaBitu** [comment]
Mě to přijde hrozně komplikovaný a pro většinu uživatelů to nebude pochopitelný. Jestli to ale správně chápu, tak tento požadavek stejně existuje jen proto, že dáváte do složky 1 fotku jako náhledovou - tedy #54. Radši bych se bavil o tom, zda kdyby byl nějaký lepší mechanismus jak udělat náhledové fotky, tak jestli tohle není zbytečné.

**Comment by GenaBitu** [comment]
Pokud není nikdo proti, uzavřel bych tento ticket a přesměrovsal ho na #54

**Comment by kalich5** [comment]
To řazení podle mě není pořád vyřešený.

**Comment by GenaBitu** [comment]
Ano, není. Ale já mám pořád pocit, že tohle issue je jen symptom toho, jak dáváme do složky 1 fotku, aby se použila jako náhledová. Tedy pokud vyřešíme #54, tak tohle už nebude problém. Navíc v současné chvíli si můžeš u každé individuální galerie nastavit řazení jak složek, tak obrázků.

Tedy za mě to vidím tak, že toto issue není třeba řešit, naopak jsem prioritizoval #54.
 
Pokud nesouhlasíš, tak je pravděpodobné, že jsem stále nepochopil tvůj use-case, tedy mi ho prosím vysvětli znovu.
