### ISSUE TITLE
Skrývání části názvu složek

### ISSUE THREAD

**Issue by kalich5** [skaut/skaut-google-drive-gallery#73]
Na Google drivu máme složky pojmenované třeba "20180525_Boje družin - Oddíl", aby se to pěkně řadilo podle názvu.

Na webu ale chceme, aby se zobrazoval název Galerie jen "Boje družin - Oddíl". Tedy aby vše, co je přes "_" bylo skryto. Jak v názvu, tak v navigaci mezi složkami.

V nastavení by měla být i možnost, si zvolit jaký znak použiju. Někde může chtít "_" někdo "@" někdo "-"...atd

**Comment by jakubpetrak** [comment]
Používáme RRRR/MM/DD_Název akce už delší dobu a jsme na to zvyklí - jelikož jsou pak akce řazeny chronologicky podle toho, jak byly a ne podle google... Takže bych taky uvítal, kdyby bylo možné skrývat část názvu před specifickým znakem (_, ...) :)

**Comment by GenaBitu** [comment]
Uzavřeno v ce959cb
