### ISSUE TITLE
The gallery is empty

### ISSUE THREAD

**Issue by galaxytass** [skaut/skaut-google-drive-gallery#759]
The version 2.10.0 seem to have broken the gallery. The error _The gallery is empty_ will show up for non-empty directories. 

It seems to break in shortcode.min.js --> `o.prototype.getSucces` where `e.directories` is filled with directories, but the property `e.directories.length` is _undefined_ and it would therefore skip the rendering of directories. The directories are shown fine on the backend. 

Currently on Wordpress version 5.5.3

**Comment by kalich5** [comment]
Did you try to reinstall? Reconnecting to Google? I have it on several websites and without any problems. It also works for me from WP 5.6.

**Comment by marekdedic** [comment]
Hi,
I cannot reproduce the issue either. Do you have any example? If you don't want to post it here, please send it to developer@dedic.eu

**Comment by galaxytass** [comment]
Hi,
The problem occurs when there are empty subfolders. So in my drive I have the following folders:  
/Test/Subfolder 1/
/Test/Subfolder 2/ 

_Subfolder 1_ contains some pictures and/or videos. `Subfolder 2` is completely empty. The problem is that when opening the _Test_ folder it shows that the gallery is empty, however it does contain two folders. In the root folder it even shows that the _Test_ folder has two subdirectories. 

I hope that you can now reproduce this problem.

**Comment by marekdedic** [comment]
Hi,
no, I did what you describe and I don't see `Subfolder 2` when I open `Test`.

Is there anything else that could narrow this down?

**Comment by galaxytass** [comment]
Hi, 
I did some testing and it does somehow matter which of the two folders is empty. So maybe you could try the other way around and make Subfolder 1 empty and place a picture in Subfolder 2. 

I hope you could reproduce it now!

**Comment by marekdedic** [comment]
Ha, I reproduced it!

**Comment by marekdedic** [comment]
Thanks for the help reproducing it, turns out the ordering of the directories really was the culprit :+1:
