### ISSUE TITLE
FEATURE REQUEST - Pass parameters to the short code

### ISSUE THREAD

**Issue by mayurjobanputra** [skaut/skaut-google-drive-gallery#779]
I would love to see the ability to pass parameters to the shortcode like image min/max file size (resolution or file size), video on/off and limit results (index).

Awesome plugin!

**Comment by marekdedic** [comment]
Hi, this is already possible I think... At least it used to be.

On the other hand, please do use the block instead of the shortcode. Shortcodes are "on life-support" and probably will get removed from the plugin eventually...

**Comment by marekdedic** [comment]
A bit unwieldy, but see https://github.com/skaut/skaut-google-drive-gallery/blob/1498b222fbe73569ac1c21041850b0c427398d74/src/php/class-options.php#L181-L197 for the option names to use (first parameter)

**Comment by mayurjobanputra** [comment]
I tried a few parameters into the shortcode, but none worked for me

[sgdg path="[wpv-post-id]" image_ordering="descending"]
[sgdg path="[wpv-post-id]" image_ordering="ascending"]
[sgdg path="[wpv-post-id]" dir_ordering="ascending"]
[sgdg path="[wpv-post-id]" dir_ordering="descending"]

**Comment by marekdedic** [comment]
Aah, ordering is a bit more complicated...
Try
`[sgdg path="[wpv-post-id]" image_ordering_by="name" image_ordering_order="descending"]`

**Comment by mayurjobanputra** [comment]
OK thats great and it works. By the way, I featured this plugin in a YT video https://www.youtube.com/watch?v=Dc8fZVy1srU

**Comment by marekdedic** [comment]
Hmm, interesting use-case together with toolset :+1:
