### ISSUE TITLE
Number of images in directory is capped at 1000

### ISSUE THREAD

**Issue by GenaBitu** [skaut/skaut-google-drive-gallery#78]

**Comment by kalich5** [comment]
takže když je víc jak 1000 fotek... nic se nezobrazí?

**Comment by GenaBitu** [comment]
Opraveno - nyní se zobrazí "1000+" - zobrazení přesného počtu by vyžadovalo více requestů na Google a to za to nestojí.

**Comment by kalich5** [comment]
Souhlasím, galerii 1000+ úplně stačí :D
