### ISSUE TITLE
Item Spacing Issues

### ISSUE THREAD

**Issue by mauricekindermann** [skaut/skaut-google-drive-gallery#80]
Item spacing doesn't appear to work all that well, I set it to 3px, see below: 

![2018-09-14_1102](https://user-images.githubusercontent.com/3828998/45523654-c8ef1f00-b80d-11e8-870e-86df9b0e4d73.png)

Switching to a well-used JS gallery like [Masonry](https://masonry.desandro.com/) might be a good move forward:

**Comment by GenaBitu** [comment]
Hi, could you please give us a link to a broken gallery? If you don't feel comfortable posting it online, could you please send it to genabitu@gmail.com?

Thank you

**Comment by GenaBitu** [comment]
Just to be clear, we were using masonry previously, but didn't like its layout, which is vertical. We concluded that this horizontal layout is much more intuitive, however it means rolling own solution (or at least I don't know of any well-used library for this layout - if you know of any, I'd like to hear that).

**Comment by GenaBitu** [comment]
Hey, the issue was caused by something on your webpage (a theme or a plugin, something called "flo" maybe?) overriding the styles from this plugin. Anyway, I was able to fix the issue, thanks for the report.
