### ISSUE TITLE
Nenačtení galerie - vypnuté "Počty položek ve složkách"

### ISSUE THREAD

**Issue by jakubpetrak** [skaut/skaut-google-drive-gallery#82]
Při vypnutí (skrytí) možnosti "Počty položek ve složkách" se galerie obsahující složky nenačtou a pouze se točí kolečko. Pokud shortcode vede na poslední složku ve stromu, tak se z ní fotky načtou... Při zobrazení počtu položek ve složkách vše funguje jak má.

**Comment by GenaBitu** [comment]
Opraveno ve verzi 2.3.1 - díky za bugreport!
