### ISSUE TITLE
Náhledové obrázky

### ISSUE THREAD

**Issue by kalich5** [skaut/skaut-google-drive-gallery#85]
https://github.com/jakubpetrak
Náhledové obrázky z Google drive k příspěvků.
Aby se dal vybrat obrázek, plugin ho sám stáhnul do interní galerie a přidal jako náhledový u příspěvku.

**Comment by GenaBitu** [comment]
To mi přijde jako fajn doplňující funkčnost, která ale za mě není úplně vysoko v prioritách. Tedy zatím nechávám otevřené pull requestům a pokud si to nikdo nevezme, v budoucnu bych se k tomu vrátil.

**Comment by marekdedic** [comment]
Closed in favor of #191.
