### ISSUE TITLE
Unicode page names break gallery

### ISSUE THREAD

**Issue by marekdedic** [skaut/skaut-google-drive-gallery#851]
Names like "Турция" or "Индия" seem to break the gallery.

Not exactly clear whether they're page names in WP or folder names in Drive

https://wordpress.org/support/topic/the-page-cant-be-found-it-looks-like-nothing-was-found-at-this-location

**Comment by marekdedic** [comment]
Probably fixed by #1512

**Comment by hazerha** [comment]
Marekddedic,
I make drama series websites.  when I upload drama but do not show it on the website.
This pop-up show.
   
"Oops! That page can’t be found.
It looks like nothing was found at this location. Maybe try one of the links below or a search?"
