### ISSUE TITLE
Please help me with the use of your plugin

### ISSUE THREAD

**Issue by geetesh07** [skaut/skaut-google-drive-gallery#871]
i am not able to get any file from my drive please make a video on how to do it i have added the client id etc but i am confused in root directory part please help me sir

Regards,
Geetesh

**Comment by marekdedic** [comment]
Hi,
please take a look at [the help page](https://napoveda.skaut.cz/dobryweb/en-skaut-google-drive-gallery).

**Comment by geetesh07** [comment]
I have taken a close look i am able to get photos but not videos please help

**Comment by marekdedic** [comment]
Ok,
with videos it's a bit more complicated - go to Google Drive and set them to "Anyone on the internet can view". It's a temporary requirement...

**Comment by geetesh07** [comment]
i did that but still i cannot see it

**Comment by marekdedic** [comment]
Then also please check if they're one of the supported formats - check the FAQ for that 😉

**Comment by geetesh07** [comment]
can you make a shot video about this a tutorial kind of starting from making the file public to upload! because the format is MP4 and i even tried for MKV

**Comment by geetesh07** [comment]
You can see that i have did everything properly!
![3](https://user-images.githubusercontent.com/70388959/110818396-397a3800-82b3-11eb-85bd-3b474d8fd97a.PNG)
![2](https://user-images.githubusercontent.com/70388959/110818400-3b43fb80-82b3-11eb-8489-1e8033674312.PNG)
![1](https://user-images.githubusercontent.com/70388959/110818408-3bdc9200-82b3-11eb-9dee-6e2f020c4f31.PNG)
![4](https://user-images.githubusercontent.com/70388959/110818501-544cac80-82b3-11eb-9d43-99ac237d01ca.PNG)
Please help!

**Comment by marekdedic** [comment]
Hi,
mkv is not supported, try one of these: https://en.wikipedia.org/wiki/HTML5_video#Browser_support

If you want a video tutorial, here's one (not made by us): https://www.youtube.com/watch?v=Dc8fZVy1srU

**Comment by geetesh07** [comment]
Thank you i will try again with mp4

**Comment by geetesh07** [comment]
Tried with a random MP4 video It worked, first of all thanks a loot you have saved a lot of time, although there r some playback issues but it is working just fine. Once again thanks a ton :)

**Comment by geetesh07** [comment]
Worked with shared drive too. No other plugin worked with shared drive. If possible please add option to toggle between diff qualities other wise all okay thanks a lot :-)
